<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."bank_transaction" (
    "bank_transaction_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "reconciliation_id" bigint NOT NULL,
    "reconciliation_type_id" smallint DEFAULT 1 NOT NULL,
    "order_intraday" varchar(100) NOT NULL,
    "bank_id" char(9) NOT NULL,
    "account_number" char(20) NOT NULL,
    "dohras" smallint DEFAULT 0 NOT NULL,
    "type_alias" varchar(100),
    "date0" date,
    "amount0" numeric(10, 2),
    "contractor_name" varchar(1000),
    "contractor_bank_account" char(20) NOT NULL,
    "contractor_inn0" char(12),
    "payment_purpose" varchar(4000),
    "has_vat" smallint DEFAULT 0 NOT NULL,
    "inner_ip" smallint DEFAULT 0 NOT NULL,
    "kassa_id" bigint,
    CONSTRAINT "bank_transaction_pkey" PRIMARY KEY (bank_transaction_id),
    CONSTRAINT "bank_transaction_kassa_id_key" UNIQUE (kassa_id),
    CONSTRAINT "bank_transaction_reconciliation_type_id_key" UNIQUE (reconciliation_type_id, reconciliation_id)
)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."bank_transaction" CASCADE
SQL);
    }
};
