<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.nsi_sgr_records (
    nsi_sgr_record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nsi_id uuid NOT NULL UNIQUE,
    version_id uuid,
    sgr_number varchar(100) NOT NULL UNIQUE,
    status_id uuid,
    status_type varchar(50),
    status_name text,
    serial_number varchar(100),
    document_date date,
    product_code varchar(100),
    product_name text,
    product_application text,
    manufacturer_name text,
    manufacturer_address text,
    manufacturer_country_id uuid,
    manufacturer_object jsonb,
    recipient_name text,
    recipient_inn varchar(100),
    recipient_address text,
    recipient_country_id uuid,
    country_code varchar(10),
    country_name text,
    use_area text,
    protocol text,
    norm_doc text,
    hygienic_characteristics jsonb,
    signer_name text,
    blank_version text,
    date_from date,
    date_to date,
    date_time_from timestamp(0) without time zone,
    date_time_to timestamp(0) without time zone,
    update_date_time timestamp(0) without time zone,
    source_list_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    detail_payload jsonb,
    list_synced_at timestamp(0) without time zone,
    detail_synced_at timestamp(0) without time zone,
    detail_attempts integer NOT NULL DEFAULT 0,
    detail_sync_error text,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
)
SQL);

        DB::statement('CREATE INDEX IF NOT EXISTS nsi_sgr_records_status_idx ON legal.nsi_sgr_records (status_name)');
        DB::statement('CREATE INDEX IF NOT EXISTS nsi_sgr_records_document_date_idx ON legal.nsi_sgr_records (document_date)');
        DB::statement('CREATE INDEX IF NOT EXISTS nsi_sgr_records_update_date_time_idx ON legal.nsi_sgr_records (update_date_time)');
        DB::statement('CREATE INDEX IF NOT EXISTS nsi_sgr_records_detail_pending_idx ON legal.nsi_sgr_records (nsi_sgr_record_id) WHERE detail_payload IS NULL');
        DB::statement('CREATE INDEX IF NOT EXISTS nsi_sgr_records_source_list_payload_gin_idx ON legal.nsi_sgr_records USING gin (source_list_payload)');
        DB::statement('CREATE INDEX IF NOT EXISTS nsi_sgr_records_detail_payload_gin_idx ON legal.nsi_sgr_records USING gin (detail_payload)');

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.nsi_sgr_import_state (
    state_key varchar(50) PRIMARY KEY,
    dictionary_code varchar(20) NOT NULL DEFAULT '1995',
    actual_date date NOT NULL,
    total_count integer,
    next_offset integer NOT NULL DEFAULT 0,
    page_limit integer NOT NULL DEFAULT 1000,
    last_success_offset integer,
    last_error_offset integer,
    last_error text,
    last_started_at timestamp(0) without time zone,
    last_finished_at timestamp(0) without time zone,
    last_success_at timestamp(0) without time zone,
    last_error_at timestamp(0) without time zone,
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
)
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS legal.nsi_sgr_import_state');
        DB::statement('DROP TABLE IF EXISTS legal.nsi_sgr_records');
    }
};
