<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.cash_operation_rules (
    cash_operation_rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    legal_id varchar(12) NOT NULL,
    contractor_inn varchar(12) NOT NULL,
    article_id smallint NOT NULL,
    direction varchar(20) DEFAULT 'incoming' NOT NULL,
    valid_from date,
    valid_to date,
    priority integer DEFAULT 100 NOT NULL,
    description_template varchar(1000),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT cash_operation_rules_direction_check CHECK (direction IN ('incoming', 'outgoing')),
    CONSTRAINT cash_operation_rules_contractor_inn_not_empty_check CHECK (btrim(contractor_inn) <> ''),
    CONSTRAINT cash_operation_rules_valid_period_check CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CONSTRAINT cash_operation_rules_legal_id_fkey FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id),
    CONSTRAINT cash_operation_rules_article_id_fkey FOREIGN KEY (article_id) REFERENCES legal.kassa_article(article_id)
)
SQL);

        DB::statement('CREATE INDEX IF NOT EXISTS cash_operation_rules_match_idx ON legal.cash_operation_rules (is_active, legal_id, contractor_inn, direction, priority)');

        DB::statement(<<<'SQL'
INSERT INTO legal.kassa_article (article)
VALUES ('Вайлдберриз'), ('Озон')
ON CONFLICT (article) DO NOTHING
SQL);

        DB::statement(<<<'SQL'
INSERT INTO legal.cash_operation_rules (
    name,
    legal_id,
    contractor_inn,
    article_id,
    direction,
    priority,
    description_template,
    metadata
)
SELECT
    article.article || ' → ' || legal.legal_name,
    legal.legal_id,
    marketplace.contractor_inn,
    article.article_id,
    'incoming',
    100,
    'Поступление от ' || article.article,
    jsonb_build_object('seeded', true, 'marketplace', marketplace.code)
FROM (VALUES
    ('wb', '7721546864', 'Вайлдберриз'),
    ('ozon', '7704217370', 'Озон')
) AS marketplace(code, contractor_inn, article_name)
JOIN legal.kassa_article article
    ON article.article = marketplace.article_name
JOIN legal.legal_own legal
    ON legal.legal_id IN ('504025873801', '521001553172')
WHERE NOT EXISTS (
    SELECT 1
    FROM legal.cash_operation_rules existing
    WHERE existing.legal_id = legal.legal_id
        AND existing.contractor_inn = marketplace.contractor_inn
        AND existing.article_id = article.article_id
        AND existing.direction = 'incoming'
)
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.cash_entries (
    cash_entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type varchar(50) NOT NULL,
    source_label varchar(255) NOT NULL,
    source_document_id bigint,
    source_document_bank_transaction_id bigint,
    kassa_id bigint,
    cash_operation_rule_id bigint,
    legal_id varchar(12) NOT NULL,
    article_id smallint,
    occurred_at timestamp without time zone NOT NULL,
    amount numeric(18,2) NOT NULL,
    currency char(3) DEFAULT '643' NOT NULL,
    description varchar(4000),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT cash_entries_source_type_check CHECK (source_type IN ('manual_kassa', 'bank_rule')),
    CONSTRAINT cash_entries_legal_id_fkey FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id),
    CONSTRAINT cash_entries_article_id_fkey FOREIGN KEY (article_id) REFERENCES legal.kassa_article(article_id),
    CONSTRAINT cash_entries_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES legal.documents(document_id) ON DELETE SET NULL,
    CONSTRAINT cash_entries_source_document_bank_transaction_id_fkey FOREIGN KEY (source_document_bank_transaction_id) REFERENCES legal.document_bank_transaction(document_bank_transaction_id) ON DELETE SET NULL,
    CONSTRAINT cash_entries_kassa_id_fkey FOREIGN KEY (kassa_id) REFERENCES legal.kassa(kassa_id) ON DELETE CASCADE,
    CONSTRAINT cash_entries_cash_operation_rule_id_fkey FOREIGN KEY (cash_operation_rule_id) REFERENCES legal.cash_operation_rules(cash_operation_rule_id) ON DELETE SET NULL
)
SQL);

        DB::statement('CREATE INDEX IF NOT EXISTS cash_entries_legal_occurred_idx ON legal.cash_entries (legal_id, occurred_at, cash_entry_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS cash_entries_article_id_idx ON legal.cash_entries (article_id)');
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS cash_entries_kassa_id_unique ON legal.cash_entries (kassa_id) WHERE kassa_id IS NOT NULL');
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS cash_entries_bank_transaction_unique ON legal.cash_entries (source_document_bank_transaction_id) WHERE source_document_bank_transaction_id IS NOT NULL');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS legal.cash_entries');
        DB::statement('DROP TABLE IF EXISTS legal.cash_operation_rules');
    }
};
