<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."kassa" (
    "kassa_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "article_id" smallint,
    "user_id" integer NOT NULL,
    "time" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "amount" integer NOT NULL,
    "description" varchar(2000) NOT NULL,
    "reconciliation_id" bigint,
    "created" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "kassa_pkey" PRIMARY KEY (kassa_id),
    CONSTRAINT "kassa_reconciliation_id_key" UNIQUE (reconciliation_id)
)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."kassa" CASCADE
SQL);
    }
};
