<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."import_runs" (
    "import_run_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "provider" varchar(50) NOT NULL,
    "type" varchar(100) NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'started',
    "source_file_name" varchar(500),
    "file_sha256" char(64),
    "file_size" bigint,
    "records_count" integer NOT NULL DEFAULT 0,
    "operations_count" integer NOT NULL DEFAULT 0,
    "error" text,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "started_at" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at" timestamp(0) without time zone,
    "created_at" timestamp(0) without time zone,
    "updated_at" timestamp(0) without time zone,
    CONSTRAINT "import_runs_pkey" PRIMARY KEY ("import_run_id"),
    CONSTRAINT "import_runs_provider_not_empty_check" CHECK (btrim("provider") <> ''),
    CONSTRAINT "import_runs_type_not_empty_check" CHECK (btrim("type") <> ''),
    CONSTRAINT "import_runs_status_not_empty_check" CHECK (btrim("status") <> '')
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "import_runs_provider_status_idx"
    ON "legal"."import_runs" ("provider", "status", "started_at")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "import_runs_file_hash_idx"
    ON "legal"."import_runs" ("file_sha256")
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."uploaded_files" (
    "uploaded_file_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "import_run_id" bigint,
    "provider" varchar(50) NOT NULL,
    "file_role" varchar(100) NOT NULL DEFAULT 'source',
    "source_file_name" varchar(500) NOT NULL,
    "stored_path" varchar(1000) NOT NULL,
    "mime_type" varchar(255),
    "file_sha256" char(64) NOT NULL,
    "file_size" bigint NOT NULL,
    "uploaded_by_user_id" bigint,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "uploaded_at" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamp(0) without time zone,
    "updated_at" timestamp(0) without time zone,
    CONSTRAINT "uploaded_files_pkey" PRIMARY KEY ("uploaded_file_id"),
    CONSTRAINT "uploaded_files_provider_not_empty_check" CHECK (btrim("provider") <> ''),
    CONSTRAINT "uploaded_files_file_role_not_empty_check" CHECK (btrim("file_role") <> ''),
    CONSTRAINT "uploaded_files_source_file_name_not_empty_check" CHECK (btrim("source_file_name") <> ''),
    CONSTRAINT "uploaded_files_stored_path_not_empty_check" CHECK (btrim("stored_path") <> ''),
    CONSTRAINT "uploaded_files_file_sha256_not_empty_check" CHECK (btrim("file_sha256") <> ''),
    CONSTRAINT "uploaded_files_import_run_fkey" FOREIGN KEY ("import_run_id")
        REFERENCES "legal"."import_runs"("import_run_id") ON UPDATE CASCADE ON DELETE SET NULL
)
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "uploaded_files_stored_path_unique"
    ON "legal"."uploaded_files" ("stored_path")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "uploaded_files_provider_hash_idx"
    ON "legal"."uploaded_files" ("provider", "file_sha256")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."uploaded_files" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."import_runs" CASCADE
SQL);
    }
};
