<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."legal_reconciliation_type" (
    "reconciliation_type_id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "reconciliation_type" varchar(100) NOT NULL,
    CONSTRAINT "legal_reconciliation_type_pkey" PRIMARY KEY (reconciliation_type_id)
)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."legal_reconciliation_type" CASCADE
SQL);
    }
};
