<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."vat_book_imports" (
    "vat_book_import_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "legal_id" bigint NOT NULL,
    "book_type" varchar(20) NOT NULL,
    "year" smallint NOT NULL,
    "quarter" smallint NOT NULL,
    "period_code" smallint NOT NULL,
    "knd" varchar(20),
    "file_identifier" varchar(255),
    "source_file_name" varchar(500) NOT NULL,
    "stored_path" varchar(1000) NOT NULL,
    "file_sha256" char(64) NOT NULL,
    "file_size" bigint NOT NULL,
    "xml_version" varchar(20),
    "program_version" varchar(255),
    "total_amount" numeric(18, 2),
    "total_amount_without_vat" numeric(18, 2),
    "total_vat_amount" numeric(18, 2),
    "entries_count" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "imported_at" timestamp without time zone DEFAULT now() NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "vat_book_imports_pkey" PRIMARY KEY ("vat_book_import_id"),
    CONSTRAINT "vat_book_imports_book_type_check" CHECK ("book_type" IN ('purchase', 'sales')),
    CONSTRAINT "vat_book_imports_quarter_check" CHECK ("quarter" BETWEEN 1 AND 4),
    CONSTRAINT "vat_book_imports_file_sha256_key" UNIQUE ("file_sha256"),
    CONSTRAINT "vat_book_imports_legal_id_fkey" FOREIGN KEY ("legal_id")
        REFERENCES "legal"."legal"("legal_id") ON UPDATE CASCADE ON DELETE RESTRICT
)
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "vat_book_imports_active_period_key"
    ON "legal"."vat_book_imports" ("legal_id", "book_type", "year", "quarter")
    WHERE "is_active"
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "vat_book_imports_period_idx"
    ON "legal"."vat_book_imports" ("year", "quarter", "book_type")
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."vat_book_entries" (
    "vat_book_entry_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "vat_book_import_id" bigint NOT NULL,
    "legal_id" bigint NOT NULL,
    "book_type" varchar(20) NOT NULL,
    "year" smallint NOT NULL,
    "quarter" smallint NOT NULL,
    "period_code" smallint NOT NULL,
    "row_number" integer NOT NULL,
    "operation_code" varchar(20),
    "invoice_number" varchar(255),
    "invoice_date" date,
    "correction_invoice_number" varchar(255),
    "correction_invoice_date" date,
    "acceptance_date" date,
    "payment_doc_number" varchar(255),
    "payment_doc_date" date,
    "contractor_name" varchar(1000),
    "contractor_inn" varchar(12),
    "contractor_kpp" varchar(20),
    "currency_code" varchar(10),
    "amount_total" numeric(18, 2),
    "amount_without_vat" numeric(18, 2),
    "vat_amount" numeric(18, 2),
    "raw_entry" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "vat_book_entries_pkey" PRIMARY KEY ("vat_book_entry_id"),
    CONSTRAINT "vat_book_entries_book_type_check" CHECK ("book_type" IN ('purchase', 'sales')),
    CONSTRAINT "vat_book_entries_import_row_key" UNIQUE ("vat_book_import_id", "row_number"),
    CONSTRAINT "vat_book_entries_import_id_fkey" FOREIGN KEY ("vat_book_import_id")
        REFERENCES "legal"."vat_book_imports"("vat_book_import_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "vat_book_entries_legal_id_fkey" FOREIGN KEY ("legal_id")
        REFERENCES "legal"."legal"("legal_id") ON UPDATE CASCADE ON DELETE RESTRICT
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "vat_book_entries_contractor_inn_idx"
    ON "legal"."vat_book_entries" ("contractor_inn")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "vat_book_entries_invoice_idx"
    ON "legal"."vat_book_entries" ("invoice_date", "invoice_number")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "vat_book_entries_period_idx"
    ON "legal"."vat_book_entries" ("legal_id", "book_type", "year", "quarter")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."vat_book_entries" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."vat_book_imports" CASCADE
SQL);
    }
};
