<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.hh_vacancies (
    hh_vacancy_id varchar(50) PRIMARY KEY,
    name varchar(500),
    employer_id varchar(50),
    employer_name varchar(500),
    alternate_url text,
    raw jsonb,
    last_synced_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
)
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.hh_negotiations (
    hh_negotiation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hh_id varchar(100),
    hh_vacancy_id varchar(50) NOT NULL REFERENCES legal.hh_vacancies(hh_vacancy_id) ON DELETE CASCADE,
    resume_id varchar(100) NOT NULL,
    candidate_name varchar(500),
    resume_title varchar(500),
    area_name varchar(255),
    status_id varchar(100),
    status_name varchar(255),
    salary_text varchar(255),
    alternate_url text,
    resume_url text,
    pdf_url text,
    pdf_path text,
    responded_at timestamp(0) without time zone,
    updated_at_hh timestamp(0) without time zone,
    downloaded_at timestamp(0) without time zone,
    analyzed_at timestamp(0) without time zone,
    analysis_score integer,
    analysis_summary text,
    analysis_flags jsonb,
    raw jsonb NOT NULL,
    resume_raw jsonb,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT hh_negotiations_vacancy_resume_unique UNIQUE (hh_vacancy_id, resume_id)
)
SQL);

        DB::statement('CREATE INDEX IF NOT EXISTS hh_negotiations_score_idx ON legal.hh_negotiations (analysis_score DESC NULLS LAST)');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_negotiations_vacancy_status_idx ON legal.hh_negotiations (hh_vacancy_id, status_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_negotiations_responded_idx ON legal.hh_negotiations (responded_at DESC NULLS LAST)');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS legal.hh_negotiations');
        DB::statement('DROP TABLE IF EXISTS legal.hh_vacancies');
    }
};
