<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."api_sync_requests" (
    "api_sync_request_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "api_sync_run_id" bigint NOT NULL,
    "provider" varchar(50) NOT NULL,
    "method" varchar(10) NOT NULL,
    "endpoint" varchar(255) NOT NULL,
    "url" text NOT NULL,
    "params" jsonb,
    "http_status" integer,
    "duration_ms" integer,
    "response_hash" char(64),
    "response_body" text,
    "response_json" jsonb,
    "error" text,
    "requested_at" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamp(0) without time zone,
    "updated_at" timestamp(0) without time zone,
    CONSTRAINT "api_sync_requests_pkey" PRIMARY KEY (api_sync_request_id),
    CONSTRAINT "api_sync_requests_run_fk" FOREIGN KEY (api_sync_run_id)
        REFERENCES legal.api_sync_runs(api_sync_run_id) ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS api_sync_requests_run_idx
    ON legal.api_sync_requests USING btree (api_sync_run_id, requested_at)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS api_sync_requests_endpoint_idx
    ON legal.api_sync_requests USING btree (provider, endpoint, http_status)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."api_sync_requests" CASCADE
SQL);
    }
};
