<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."document_party_roles" (
    "document_party_role_id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" varchar(100) NOT NULL,
    "name" varchar(255) NOT NULL,
    "description" text,
    "document_group" varchar(100),
    "is_system" boolean DEFAULT true NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "sort_order" smallint DEFAULT 100 NOT NULL,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "document_party_roles_pkey" PRIMARY KEY (document_party_role_id),
    CONSTRAINT "document_party_roles_code_key" UNIQUE (code),
    CONSTRAINT "document_party_roles_code_not_empty_check" CHECK (btrim(code::text) <> ''),
    CONSTRAINT "document_party_roles_name_not_empty_check" CHECK (btrim(name::text) <> '')
)
SQL);

        DB::statement(<<<'SQL'
INSERT INTO "legal"."document_party_roles" (
    "code",
    "name",
    "description",
    "document_group",
    "sort_order"
) VALUES
    ('party', 'Сторона', 'Универсальная сторона документа, когда роль симметрична.', null, 10),
    ('payer', 'Плательщик', 'Сторона, которая перечисляет деньги.', 'money', 20),
    ('recipient', 'Получатель', 'Сторона, которая получает деньги.', 'money', 30),
    ('seller', 'Продавец / исполнитель', 'Сторона, которая продает товар, работу или услугу.', 'primary', 40),
    ('buyer', 'Покупатель / заказчик', 'Сторона, которая покупает товар, работу или услугу.', 'primary', 50),
    ('supplier', 'Поставщик', 'Сторона, которая поставляет товар или материал.', 'primary', 60),
    ('customer', 'Заказчик', 'Сторона, которая заказывает работу, услугу или поставку.', 'primary', 70),
    ('shipper', 'Грузоотправитель', 'Сторона, отправляющая груз.', 'primary', 80),
    ('consignee', 'Грузополучатель', 'Сторона, принимающая груз.', 'primary', 90),
    ('carrier', 'Перевозчик', 'Сторона, которая перевозит груз.', 'primary', 100),
    ('agent', 'Агент', 'Агент в агентской или посреднической схеме.', 'agency', 110),
    ('principal', 'Принципал', 'Принципал в агентской или посреднической схеме.', 'agency', 120),
    ('commissioner', 'Комиссионер', 'Комиссионер в комиссионной схеме.', 'agency', 130),
    ('bank', 'Банк', 'Банк, участвующий в документе или операции.', 'money', 140),
    ('tax_authority', 'Налоговый орган', 'Налоговая или иной фискальный орган.', 'tax', 150),
    ('marketplace', 'Маркетплейс', 'Маркетплейс или площадка.', 'marketplace', 160),
    ('issuer', 'Составитель', 'Сторона, которая выпустила или составила документ.', null, 170),
    ('signer', 'Подписант', 'Физическое или юридическое лицо, подписавшее документ.', null, 180)
ON CONFLICT ("code") DO UPDATE
SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "document_group" = EXCLUDED."document_group",
    "sort_order" = EXCLUDED."sort_order",
    "updated_at" = now()
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_party_roles_document_group_idx"
    ON "legal"."document_party_roles" ("document_group")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_party_roles_active_sort_idx"
    ON "legal"."document_party_roles" ("is_active", "sort_order")
SQL);

        DB::statement(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'document_parties_role_fkey'
    ) THEN
        ALTER TABLE "legal"."document_parties"
            ADD CONSTRAINT "document_parties_role_fkey"
            FOREIGN KEY ("role")
            REFERENCES "legal"."document_party_roles"("code")
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            NOT VALID;
    END IF;
END
$$
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
ALTER TABLE "legal"."document_parties"
    DROP CONSTRAINT IF EXISTS "document_parties_role_fkey"
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."document_party_roles" CASCADE
SQL);
    }
};
