<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."api_credentials" (
    "api_credential_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "provider" varchar(50) NOT NULL,
    "credential_type" varchar(100) NOT NULL,
    "owner_type" varchar(100),
    "owner_id" varchar(100),
    "name" varchar(255),
    "encrypted_secret" text NOT NULL,
    "meta" jsonb,
    "status" varchar(20) NOT NULL DEFAULT 'active',
    "last_used_at" timestamp(0) without time zone,
    "created_at" timestamp(0) without time zone,
    "updated_at" timestamp(0) without time zone,
    CONSTRAINT "api_credentials_pkey" PRIMARY KEY (api_credential_id)
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS api_credentials_provider_status_idx
    ON legal.api_credentials USING btree (provider, status)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS api_credentials_owner_idx
    ON legal.api_credentials USING btree (owner_type, owner_id)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."api_credentials" CASCADE
SQL);
    }
};
