<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.hh_resume_analysis_batch_logs (
    hh_resume_analysis_batch_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hh_resume_analysis_batch_id bigint REFERENCES legal.hh_resume_analysis_batches(hh_resume_analysis_batch_id) ON DELETE CASCADE,
    hh_negotiation_id bigint,
    event_type varchar(100) NOT NULL,
    direction varchar(20) NOT NULL,
    endpoint varchar(500),
    status_code integer,
    custom_id varchar(255),
    payload jsonb,
    content text,
    error_message text,
    created_at timestamp(0) without time zone
)
SQL);

        DB::statement('CREATE INDEX IF NOT EXISTS hh_resume_analysis_batch_logs_batch_idx ON legal.hh_resume_analysis_batch_logs (hh_resume_analysis_batch_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_resume_analysis_batch_logs_negotiation_idx ON legal.hh_resume_analysis_batch_logs (hh_negotiation_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_resume_analysis_batch_logs_event_idx ON legal.hh_resume_analysis_batch_logs (event_type)');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS legal.hh_resume_analysis_batch_logs');
    }
};
