<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.hh_resume_analysis_batches (
    hh_resume_analysis_batch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openai_batch_id varchar(255),
    input_file_id varchar(255),
    output_file_id varchar(255),
    error_file_id varchar(255),
    status varchar(100) NOT NULL DEFAULT 'draft',
    hh_vacancy_id varchar(50),
    model varchar(100),
    total_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    failed_count integer NOT NULL DEFAULT 0,
    requested_by_user_id bigint,
    requested_from varchar(50),
    submitted_at timestamp(0) without time zone,
    last_polled_at timestamp(0) without time zone,
    completed_at timestamp(0) without time zone,
    error_message text,
    raw jsonb,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
)
SQL);

        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS hh_resume_analysis_batches_openai_batch_unique ON legal.hh_resume_analysis_batches (openai_batch_id) WHERE openai_batch_id IS NOT NULL');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_resume_analysis_batches_status_idx ON legal.hh_resume_analysis_batches (status)');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_resume_analysis_batches_vacancy_idx ON legal.hh_resume_analysis_batches (hh_vacancy_id)');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS legal.hh_resume_analysis_batches');
    }
};
