<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."vat_events" (
    "vat_event_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_system" varchar(100) DEFAULT 'accountant_vat_book'::character varying NOT NULL,
    "source_vat_book_import_id" bigint,
    "source_vat_book_entry_id" bigint,
    "legal_id" varchar(12) NOT NULL,
    "year" smallint NOT NULL,
    "quarter" smallint NOT NULL,
    "book_type" varchar(20) NOT NULL,
    "vat_direction" varchar(20) NOT NULL,
    "occurred_on" date,
    "invoice_number" varchar(255),
    "invoice_date" date,
    "contractor_name" varchar(1000),
    "contractor_inn" varchar(12),
    "contractor_kpp" varchar(20),
    "amount_total" numeric(18, 2),
    "amount_without_vat" numeric(18, 2),
    "vat_amount" numeric(18, 2) NOT NULL,
    "signed_vat_amount" numeric(18, 2) NOT NULL,
    "operation_code" varchar(20),
    "algorithm" varchar(100) DEFAULT 'accountant_vat_book_v1'::character varying NOT NULL,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "vat_events_pkey" PRIMARY KEY ("vat_event_id"),
    CONSTRAINT "vat_events_book_type_check" CHECK ("book_type" IN ('purchase', 'sales')),
    CONSTRAINT "vat_events_vat_direction_check" CHECK ("vat_direction" IN ('input', 'output')),
    CONSTRAINT "vat_events_unique_source_entry" UNIQUE ("source_system", "source_vat_book_entry_id"),
    CONSTRAINT "vat_events_source_import_fkey" FOREIGN KEY ("source_vat_book_import_id")
        REFERENCES "legal"."vat_book_imports"("vat_book_import_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "vat_events_source_entry_fkey" FOREIGN KEY ("source_vat_book_entry_id")
        REFERENCES "legal"."vat_book_entries"("vat_book_entry_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "vat_events_legal_id_fkey" FOREIGN KEY ("legal_id")
        REFERENCES "legal"."legal"("legal_id") ON UPDATE CASCADE ON DELETE RESTRICT
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "vat_events_period_idx"
    ON "legal"."vat_events" ("legal_id", "year", "quarter")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "vat_events_contractor_inn_idx"
    ON "legal"."vat_events" ("contractor_inn")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "vat_events_occurred_on_idx"
    ON "legal"."vat_events" ("occurred_on")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."vat_events" CASCADE
SQL);
    }
};
