<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."documents" (
    "document_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "document_type_id" smallint NOT NULL,
    "document_date" date,
    "document_number" text,
    "title" text,
    "amount" numeric(18, 2),
    "currency" char(3),
    "status" text NOT NULL DEFAULT 'imported',
    "source_system" text,
    "external_id" text,
    "external_hash" text,
    "source_api_sync_request_id" bigint,
    "source_file_id" bigint,
    "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "imported_at" timestamp(0) without time zone,
    "created_at" timestamp(0) without time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp(0) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "documents_pkey" PRIMARY KEY (document_id),
    CONSTRAINT "documents_status_not_empty_check" CHECK (btrim(status) <> ''),
    CONSTRAINT "documents_source_system_not_empty_check" CHECK (source_system IS NULL OR btrim(source_system) <> ''),
    CONSTRAINT "documents_external_id_not_empty_check" CHECK (external_id IS NULL OR btrim(external_id) <> ''),
    CONSTRAINT "documents_external_hash_not_empty_check" CHECK (external_hash IS NULL OR btrim(external_hash) <> ''),
    CONSTRAINT "documents_document_type_id_fkey" FOREIGN KEY (document_type_id)
        REFERENCES legal.document_types(document_type_id)
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "documents_document_type_id_idx"
    ON "legal"."documents" ("document_type_id")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "documents_document_date_idx"
    ON "legal"."documents" ("document_date")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "documents_source_system_external_id_idx"
    ON "legal"."documents" ("source_system", "external_id")
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "documents_source_system_external_id_unique"
    ON "legal"."documents" ("document_type_id", "source_system", "external_id")
    WHERE "source_system" IS NOT NULL AND "external_id" IS NOT NULL
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "documents_source_system_external_hash_unique"
    ON "legal"."documents" ("source_system", "external_hash")
    WHERE "source_system" IS NOT NULL AND "external_hash" IS NOT NULL
SQL);

        DB::statement(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'document_parties_document_id_fkey'
    ) THEN
        ALTER TABLE "legal"."document_parties"
            ADD CONSTRAINT "document_parties_document_id_fkey"
            FOREIGN KEY ("document_id")
            REFERENCES "legal"."documents"("document_id")
            ON UPDATE CASCADE
            ON DELETE CASCADE
            NOT VALID;
    END IF;
END $$;
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
ALTER TABLE "legal"."document_parties"
    DROP CONSTRAINT IF EXISTS "document_parties_document_id_fkey"
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."documents" CASCADE
SQL);
    }
};
