<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."counterparty_opening_balances" (
    "counterparty_opening_balance_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "legal_id" bigint NOT NULL,
    "contractor_inn" varchar(12) NOT NULL,
    "starts_on" date NOT NULL,
    "amount" numeric(18, 2) NOT NULL,
    "source" varchar(255),
    "comment" text,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "counterparty_opening_balances_pkey" PRIMARY KEY ("counterparty_opening_balance_id"),
    CONSTRAINT "counterparty_opening_balances_legal_contractor_start_key" UNIQUE ("legal_id", "contractor_inn", "starts_on"),
    CONSTRAINT "counterparty_opening_balances_legal_id_fkey" FOREIGN KEY ("legal_id")
        REFERENCES "legal"."legal"("legal_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT "counterparty_opening_balances_contractor_inn_not_empty_check" CHECK (btrim("contractor_inn") <> '')
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "counterparty_opening_balances_contractor_idx"
    ON "legal"."counterparty_opening_balances" ("contractor_inn", "legal_id", "starts_on")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."counterparty_opening_balances" CASCADE
SQL);
    }
};
