<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."api_sync_runs" (
    "api_sync_run_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "provider" varchar(50) NOT NULL,
    "type" varchar(100) NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'started',
    "period_from" date,
    "period_till" date,
    "accounts_count" integer NOT NULL DEFAULT 0,
    "operations_count" integer NOT NULL DEFAULT 0,
    "requests_count" integer NOT NULL DEFAULT 0,
    "error" text,
    "started_at" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at" timestamp(0) without time zone,
    "created_at" timestamp(0) without time zone,
    "updated_at" timestamp(0) without time zone,
    CONSTRAINT "api_sync_runs_pkey" PRIMARY KEY (api_sync_run_id)
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS api_sync_runs_provider_status_idx
    ON legal.api_sync_runs USING btree (provider, status, started_at)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."api_sync_runs" CASCADE
SQL);
    }
};
