<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."money_edges" (
    "money_edge_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_document_id" bigint NOT NULL,
    "source_document_bank_transaction_id" bigint NOT NULL,
    "payer_document_party_id" bigint,
    "recipient_document_party_id" bigint,
    "occurred_on" date,
    "amount" numeric(18, 2) NOT NULL,
    "currency" char(3) DEFAULT 'RUB'::bpchar NOT NULL,
    "payer_name_snapshot" varchar(1000),
    "payer_inn_snapshot" varchar(12),
    "recipient_name_snapshot" varchar(1000),
    "recipient_inn_snapshot" varchar(12),
    "payment_purpose" varchar(4000),
    "algorithm" varchar(100) DEFAULT 'bank_operation_v1'::character varying NOT NULL,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "money_edges_pkey" PRIMARY KEY (money_edge_id),
    CONSTRAINT "money_edges_source_bank_transaction_key" UNIQUE (source_document_bank_transaction_id),
    CONSTRAINT "money_edges_amount_positive_check" CHECK (amount >= 0),
    CONSTRAINT "money_edges_source_document_id_fkey" FOREIGN KEY (source_document_id)
        REFERENCES "legal"."documents"("document_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "money_edges_source_document_bank_transaction_id_fkey" FOREIGN KEY (source_document_bank_transaction_id)
        REFERENCES "legal"."document_bank_transaction"("document_bank_transaction_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "money_edges_payer_document_party_id_fkey" FOREIGN KEY (payer_document_party_id)
        REFERENCES "legal"."document_parties"("document_party_id") ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT "money_edges_recipient_document_party_id_fkey" FOREIGN KEY (recipient_document_party_id)
        REFERENCES "legal"."document_parties"("document_party_id") ON UPDATE CASCADE ON DELETE SET NULL
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "money_edges_occurred_on_idx"
    ON "legal"."money_edges" ("occurred_on")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "money_edges_payer_inn_idx"
    ON "legal"."money_edges" ("payer_inn_snapshot")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "money_edges_recipient_inn_idx"
    ON "legal"."money_edges" ("recipient_inn_snapshot")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."money_edges" CASCADE
SQL);
    }
};
