<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."document_bank_transaction" (
    "document_bank_transaction_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "document_id" bigint NOT NULL,
    "bank_transaction_id" bigint,
    "bank_account_id" bigint NOT NULL,
    "bank_id" char(9) NOT NULL,
    "account_number" char(20) NOT NULL,
    "external_operation_id" varchar(100) NOT NULL,
    "external_id" varchar(100),
    "operation_date" date,
    "draw_date" date,
    "charge_date" date,
    "order_intraday" varchar(100),
    "amount" numeric(18, 2),
    "signed_amount" numeric(18, 2),
    "currency" char(3),
    "payer_name" varchar(1000),
    "payer_inn" varchar(12),
    "payer_kpp" varchar(9),
    "payer_account" char(20),
    "payer_bic" char(9),
    "payer_bank" varchar(500),
    "payer_corr_account" char(20),
    "recipient_name" varchar(1000),
    "recipient_inn" varchar(12),
    "recipient_kpp" varchar(9),
    "recipient_account" char(20),
    "recipient_bic" char(9),
    "recipient_bank" varchar(500),
    "recipient_corr_account" char(20),
    "payment_purpose" varchar(4000),
    "payment_type" varchar(100),
    "operation_type" varchar(100),
    "uin" varchar(100),
    "creator_status" varchar(100),
    "kbk" varchar(100),
    "oktmo" varchar(100),
    "tax_evidence" varchar(100),
    "tax_period" varchar(100),
    "tax_doc_number" varchar(100),
    "tax_doc_date" varchar(100),
    "tax_type" varchar(100),
    "execution_order" varchar(5),
    "raw_payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "document_bank_transaction_pkey" PRIMARY KEY (document_bank_transaction_id),
    CONSTRAINT "document_bank_transaction_document_id_key" UNIQUE (document_id),
    CONSTRAINT "document_bank_transaction_account_operation_key" UNIQUE (bank_account_id, external_operation_id),
    CONSTRAINT "document_bank_transaction_operation_id_not_empty_check" CHECK (btrim(external_operation_id::text) <> ''),
    CONSTRAINT "document_bank_transaction_document_id_fkey" FOREIGN KEY (document_id)
        REFERENCES "legal"."documents"("document_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "document_bank_transaction_bank_account_id_fkey" FOREIGN KEY (bank_account_id)
        REFERENCES "legal"."bank_account"("bank_account_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT "document_bank_transaction_bank_transaction_id_fkey" FOREIGN KEY (bank_transaction_id)
        REFERENCES "legal"."bank_transaction"("bank_transaction_id") ON UPDATE CASCADE ON DELETE SET NULL
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_bank_transaction_operation_date_idx"
    ON "legal"."document_bank_transaction" ("operation_date")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_bank_transaction_payer_inn_idx"
    ON "legal"."document_bank_transaction" ("payer_inn")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_bank_transaction_recipient_inn_idx"
    ON "legal"."document_bank_transaction" ("recipient_inn")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."document_bank_transaction" CASCADE
SQL);
    }
};
