<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."document_parties" (
    "document_party_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "document_id" bigint NOT NULL,
    "party_id" bigint,
    "role" varchar(100) NOT NULL,
    "role_index" smallint DEFAULT 1 NOT NULL,
    "name_snapshot" varchar(1000) NOT NULL,
    "inn_snapshot" varchar(12),
    "kpp_snapshot" varchar(9),
    "country_code" char(2) DEFAULT 'RU'::bpchar NOT NULL,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "document_parties_pkey" PRIMARY KEY (document_party_id),
    CONSTRAINT "document_parties_document_role_index_key" UNIQUE (document_id, role, role_index),
    CONSTRAINT "document_parties_role_not_empty_check" CHECK (btrim(role::text) <> ''::text),
    CONSTRAINT "document_parties_name_snapshot_not_empty_check" CHECK (btrim(name_snapshot::text) <> ''::text)
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_parties_document_id_idx"
    ON "legal"."document_parties" ("document_id")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_parties_party_id_idx"
    ON "legal"."document_parties" ("party_id")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_parties_inn_snapshot_idx"
    ON "legal"."document_parties" ("inn_snapshot")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_parties_role_idx"
    ON "legal"."document_parties" ("role")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."document_parties" CASCADE
SQL);
    }
};
