<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS legal.hh_browser_captures (
    hh_browser_capture_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key varchar(64) NOT NULL UNIQUE,
    source varchar(100) NOT NULL,
    page_url text NOT NULL,
    page_title text,
    hh_vacancy_id varchar(50),
    vacancy_title varchar(500),
    vacancy_url text,
    resume_id varchar(100),
    candidate_name varchar(500),
    candidate_resume_url text,
    candidate_location varchar(255),
    candidate_age varchar(100),
    response_status varchar(255),
    cover_letter text,
    raw_text text,
    raw_links jsonb NOT NULL DEFAULT '[]'::jsonb,
    payload jsonb NOT NULL,
    captured_by_user_id bigint REFERENCES legal.laravel_users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    captured_ip inet,
    captured_user_agent text,
    captured_at timestamp(0) without time zone NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
)
SQL);

        DB::statement('CREATE INDEX IF NOT EXISTS hh_browser_captures_vacancy_idx ON legal.hh_browser_captures (hh_vacancy_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_browser_captures_resume_idx ON legal.hh_browser_captures (resume_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS hh_browser_captures_captured_at_idx ON legal.hh_browser_captures (captured_at DESC)');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS legal.hh_browser_captures');
    }
};
