<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."legal_brand" (
    "brand_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "legal_id_owner" varchar(12),
    "brand" varchar(200) NOT NULL,
    "comment" varchar(3000),
    CONSTRAINT "legal_brand_pkey" PRIMARY KEY (brand_id)
)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."legal_brand" CASCADE
SQL);
    }
};
