<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."kassa_article" (
    "article_id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "article" varchar(100) NOT NULL,
    CONSTRAINT "kassa_article_pkey" PRIMARY KEY (article_id),
    CONSTRAINT "kassa_article_article_key" UNIQUE (article)
)
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."kassa_article" CASCADE
SQL);
    }
};
