<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."document_types" (
    "document_type_id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" text NOT NULL,
    "name" text NOT NULL,
    "document_group" text NOT NULL,
    "is_primary" boolean DEFAULT false NOT NULL,
    "is_tax_document" boolean DEFAULT false NOT NULL,
    "is_money_document" boolean DEFAULT false NOT NULL,
    "is_inventory_document" boolean DEFAULT false NOT NULL,
    "is_contract_document" boolean DEFAULT false NOT NULL,
    "creates_accounting_events" boolean DEFAULT false NOT NULL,
    "creates_management_events" boolean DEFAULT false NOT NULL,
    "creates_tax_events" boolean DEFAULT false NOT NULL,
    "requires_parties" boolean DEFAULT true NOT NULL,
    "requires_lines" boolean DEFAULT false NOT NULL,
    "supports_corrections" boolean DEFAULT false NOT NULL,
    "supports_files" boolean DEFAULT true NOT NULL,
    "default_direction" text,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "document_types_pkey" PRIMARY KEY (document_type_id),
    CONSTRAINT "document_types_code_key" UNIQUE (code)
)
SQL);

        DB::statement(<<<'SQL'
INSERT INTO "legal"."document_types" (
    "code",
    "name",
    "document_group",
    "is_primary",
    "is_tax_document",
    "is_money_document",
    "is_inventory_document",
    "is_contract_document",
    "creates_accounting_events",
    "creates_management_events",
    "creates_tax_events",
    "requires_parties",
    "requires_lines",
    "supports_corrections",
    "supports_files",
    "default_direction"
) VALUES
    ('contract', 'Договор', 'contract', false, false, false, false, true, false, false, false, true, false, true, true, null),
    ('additional_agreement', 'Дополнительное соглашение', 'contract', false, false, false, false, true, false, false, false, true, false, true, true, null),
    ('invoice_for_payment', 'Счет на оплату', 'contract', false, false, false, false, false, false, true, false, true, true, false, true, null),
    ('upd', 'УПД', 'primary', true, true, false, true, false, true, true, true, true, true, true, true, null),
    ('correction_upd', 'Корректировочный УПД', 'primary', true, true, false, true, false, true, true, true, true, true, true, true, null),
    ('act', 'Акт', 'primary', true, false, false, false, false, true, true, false, true, true, true, true, null),
    ('correction_act', 'Корректировочный акт', 'primary', true, false, false, false, false, true, true, false, true, true, true, true, null),
    ('vat_purchase_book', 'Книга покупок', 'tax', false, true, false, false, false, true, false, true, true, true, false, true, 'incoming'),
    ('vat_sales_book', 'Книга продаж', 'tax', false, true, false, false, false, true, false, true, true, true, false, true, 'outgoing'),
    ('bank_statement', 'Банковская выписка', 'money', false, false, true, false, false, true, true, false, true, true, false, true, null),
    ('bank_operation', 'Банковская операция', 'money', false, false, true, false, false, true, true, false, true, false, false, false, null),
    ('cash_operation', 'Кассовая операция', 'money', true, false, true, false, false, true, true, false, true, false, true, true, null),
    ('marketplace_commissioner_report', 'Отчет комиссионера маркетплейса', 'marketplace', true, true, false, true, false, true, true, true, true, true, true, true, null),
    ('marketplace_sales_report', 'Отчет о продажах маркетплейса', 'marketplace', false, false, false, true, false, false, true, false, true, true, true, true, null),
    ('marketplace_payout_report', 'Отчет о выплате маркетплейса', 'marketplace', false, false, true, false, false, true, true, false, true, true, false, true, null),
    ('production_order', 'Производственное задание', 'production', false, false, false, true, false, false, true, false, true, true, true, true, null),
    ('inventory_transfer', 'Перемещение ТМЦ', 'inventory', true, false, false, true, false, true, true, false, true, true, true, true, 'internal'),
    ('inventory_write_off', 'Списание ТМЦ', 'inventory', true, false, false, true, false, true, true, false, true, true, true, true, 'outgoing'),
    ('stocktaking', 'Инвентаризация', 'inventory', true, false, false, true, false, true, true, false, true, true, true, true, 'internal'),
    ('tax_payment', 'Уплата налога', 'tax', true, true, true, false, false, true, true, true, true, false, true, true, 'outgoing'),
    ('tax_accrual', 'Начисление налога', 'tax', false, true, false, false, false, true, true, true, true, false, true, false, null),
    ('manual_adjustment', 'Ручная корректировка', 'system', false, false, false, false, false, true, true, true, true, false, true, false, null)
ON CONFLICT ("code") DO UPDATE
SET
    "name" = EXCLUDED."name",
    "document_group" = EXCLUDED."document_group",
    "is_primary" = EXCLUDED."is_primary",
    "is_tax_document" = EXCLUDED."is_tax_document",
    "is_money_document" = EXCLUDED."is_money_document",
    "is_inventory_document" = EXCLUDED."is_inventory_document",
    "is_contract_document" = EXCLUDED."is_contract_document",
    "creates_accounting_events" = EXCLUDED."creates_accounting_events",
    "creates_management_events" = EXCLUDED."creates_management_events",
    "creates_tax_events" = EXCLUDED."creates_tax_events",
    "requires_parties" = EXCLUDED."requires_parties",
    "requires_lines" = EXCLUDED."requires_lines",
    "supports_corrections" = EXCLUDED."supports_corrections",
    "supports_files" = EXCLUDED."supports_files",
    "default_direction" = EXCLUDED."default_direction",
    "updated_at" = now()
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."document_types" CASCADE
SQL);
    }
};
