<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."accountant_report_link_types" (
    "accountant_report_link_type_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "alias" varchar(100) NOT NULL,
    "name" varchar(255) NOT NULL,
    "description" text,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "accountant_report_link_types_pkey" PRIMARY KEY ("accountant_report_link_type_id"),
    CONSTRAINT "accountant_report_link_types_alias_key" UNIQUE ("alias"),
    CONSTRAINT "accountant_report_link_types_alias_not_empty_check" CHECK (btrim("alias") <> '')
)
SQL);

        DB::statement(<<<'SQL'
INSERT INTO "legal"."accountant_report_link_types" ("alias", "name", "description")
VALUES
    ('payment_closes_vat_book_entry', 'Payment closes VAT book entry', 'Bank payment closes an accountant VAT book entry.'),
    ('payment_is_advance_for_vat_book_entry', 'Payment is advance for VAT book entry', 'Bank payment is treated as an advance later closed by an accountant VAT book entry.'),
    ('refund_reverses_vat_book_entry', 'Refund reverses VAT book entry', 'Bank refund reverses or reduces an accountant VAT book entry.'),
    ('manual_match', 'Manual match', 'Manual link made by a user when the exact accounting meaning is decided outside the algorithm.')
ON CONFLICT ("alias") DO UPDATE
SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "updated_at" = now()
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."accountant_report_links" (
    "accountant_report_link_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "accountant_report_link_type_id" bigint NOT NULL,
    "vat_book_entry_id" bigint NOT NULL,
    "document_bank_transaction_id" bigint NOT NULL,
    "amount" numeric(18, 2) NOT NULL,
    "vat_amount" numeric(18, 2),
    "currency" char(3) DEFAULT 'RUB'::bpchar NOT NULL,
    "matched_on" date,
    "confidence" numeric(5, 4),
    "source" varchar(50) DEFAULT 'manual'::character varying NOT NULL,
    "algorithm" varchar(100),
    "notes" text,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "accountant_report_links_pkey" PRIMARY KEY ("accountant_report_link_id"),
    CONSTRAINT "accountant_report_links_amount_non_negative_check" CHECK ("amount" >= 0),
    CONSTRAINT "accountant_report_links_vat_amount_non_negative_check" CHECK ("vat_amount" IS NULL OR "vat_amount" >= 0),
    CONSTRAINT "accountant_report_links_confidence_check" CHECK ("confidence" IS NULL OR ("confidence" >= 0 AND "confidence" <= 1)),
    CONSTRAINT "accountant_report_links_source_check" CHECK ("source" IN ('manual', 'algorithm', 'import')),
    CONSTRAINT "accountant_report_links_type_id_fkey" FOREIGN KEY ("accountant_report_link_type_id")
        REFERENCES "legal"."accountant_report_link_types"("accountant_report_link_type_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT "accountant_report_links_vat_book_entry_id_fkey" FOREIGN KEY ("vat_book_entry_id")
        REFERENCES "legal"."vat_book_entries"("vat_book_entry_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "accountant_report_links_document_bank_transaction_id_fkey" FOREIGN KEY ("document_bank_transaction_id")
        REFERENCES "legal"."document_bank_transaction"("document_bank_transaction_id") ON UPDATE CASCADE ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "accountant_report_links_vat_book_entry_idx"
    ON "legal"."accountant_report_links" ("vat_book_entry_id")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "accountant_report_links_bank_transaction_idx"
    ON "legal"."accountant_report_links" ("document_bank_transaction_id")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "accountant_report_links_type_idx"
    ON "legal"."accountant_report_links" ("accountant_report_link_type_id")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."accountant_report_links" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."accountant_report_link_types" CASCADE
SQL);
    }
};
