<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_records" (
    "source_record_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_system" varchar(100) NOT NULL,
    "source_channel" varchar(100),
    "source_record_type" varchar(100) NOT NULL,
    "external_id" text,
    "external_hash" char(64),
    "source_api_sync_request_id" bigint,
    "source_vat_book_entry_id" bigint,
    "source_file_path" varchar(1000),
    "received_at" timestamp without time zone,
    "recorded_at" timestamp without time zone,
    "raw_payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_records_pkey" PRIMARY KEY ("source_record_id"),
    CONSTRAINT "source_records_source_system_not_empty_check" CHECK (btrim("source_system") <> ''),
    CONSTRAINT "source_records_source_record_type_not_empty_check" CHECK (btrim("source_record_type") <> ''),
    CONSTRAINT "source_records_external_id_not_empty_check" CHECK ("external_id" IS NULL OR btrim("external_id") <> ''),
    CONSTRAINT "source_records_external_hash_not_empty_check" CHECK ("external_hash" IS NULL OR btrim("external_hash") <> ''),
    CONSTRAINT "source_records_api_sync_request_fkey" FOREIGN KEY ("source_api_sync_request_id")
        REFERENCES "legal"."api_sync_requests"("api_sync_request_id") ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT "source_records_vat_book_entry_fkey" FOREIGN KEY ("source_vat_book_entry_id")
        REFERENCES "legal"."vat_book_entries"("vat_book_entry_id") ON UPDATE CASCADE ON DELETE SET NULL
)
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "source_records_external_id_unique"
    ON "legal"."source_records" ("source_system", "source_record_type", "external_id")
    WHERE "external_id" IS NOT NULL
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "source_records_external_hash_unique"
    ON "legal"."source_records" ("source_system", "source_record_type", "external_hash")
    WHERE "external_hash" IS NOT NULL
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "source_records_type_idx"
    ON "legal"."source_records" ("source_record_type", "source_system")
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "source_records_received_at_idx"
    ON "legal"."source_records" ("received_at")
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_record_parties" (
    "source_record_party_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_record_id" bigint NOT NULL,
    "source_party_role" varchar(100) NOT NULL,
    "role_index" smallint DEFAULT 1 NOT NULL,
    "party_name" varchar(1000),
    "inn" varchar(12),
    "kpp" varchar(20),
    "account_number" varchar(34),
    "bank_bic" varchar(20),
    "bank_name" varchar(500),
    "address" text,
    "raw_payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_record_parties_pkey" PRIMARY KEY ("source_record_party_id"),
    CONSTRAINT "source_record_parties_role_not_empty_check" CHECK (btrim("source_party_role") <> ''),
    CONSTRAINT "source_record_parties_record_role_index_key" UNIQUE ("source_record_id", "source_party_role", "role_index"),
    CONSTRAINT "source_record_parties_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "source_record_parties_inn_idx"
    ON "legal"."source_record_parties" ("inn")
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_record_amounts" (
    "source_record_amount_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_record_id" bigint NOT NULL,
    "amount_type" varchar(100) NOT NULL,
    "amount" numeric(18, 2) NOT NULL,
    "currency" char(3) DEFAULT 'RUB'::bpchar NOT NULL,
    "tax_rate" numeric(8, 4),
    "raw_payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_record_amounts_pkey" PRIMARY KEY ("source_record_amount_id"),
    CONSTRAINT "source_record_amounts_type_not_empty_check" CHECK (btrim("amount_type") <> ''),
    CONSTRAINT "source_record_amounts_record_type_key" UNIQUE ("source_record_id", "amount_type"),
    CONSTRAINT "source_record_amounts_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_record_files" (
    "source_record_file_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_record_id" bigint NOT NULL,
    "file_role" varchar(100) NOT NULL,
    "source_file_name" varchar(500),
    "stored_path" varchar(1000) NOT NULL,
    "mime_type" varchar(255),
    "file_sha256" char(64),
    "file_size" bigint,
    "encoding" varchar(100),
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_record_files_pkey" PRIMARY KEY ("source_record_file_id"),
    CONSTRAINT "source_record_files_role_not_empty_check" CHECK (btrim("file_role") <> ''),
    CONSTRAINT "source_record_files_stored_path_not_empty_check" CHECK (btrim("stored_path") <> ''),
    CONSTRAINT "source_record_files_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "source_record_files_record_hash_unique"
    ON "legal"."source_record_files" ("source_record_id", "file_sha256")
    WHERE "file_sha256" IS NOT NULL
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_record_product_marks" (
    "source_record_product_mark_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_record_id" bigint NOT NULL,
    "mark_code" text NOT NULL,
    "mark_type" varchar(100),
    "product_group" varchar(100),
    "gtin" varchar(14),
    "serial_number" text,
    "raw_payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_record_product_marks_pkey" PRIMARY KEY ("source_record_product_mark_id"),
    CONSTRAINT "source_record_product_marks_code_not_empty_check" CHECK (btrim("mark_code") <> ''),
    CONSTRAINT "source_record_product_marks_record_code_key" UNIQUE ("source_record_id", "mark_code"),
    CONSTRAINT "source_record_product_marks_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "source_record_product_marks_code_idx"
    ON "legal"."source_record_product_marks" ("mark_code")
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_record_bank_details" (
    "source_record_id" bigint NOT NULL,
    "bank_account_id" bigint,
    "bank_id" char(9),
    "account_number" char(20),
    "external_operation_id" varchar(100),
    "operation_date" date,
    "draw_date" date,
    "charge_date" date,
    "order_intraday" varchar(100),
    "payment_purpose" varchar(4000),
    "payment_type" varchar(100),
    "operation_type" varchar(100),
    "signed_amount" numeric(18, 2),
    "saldo" numeric(18, 2),
    "tax_fields" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_record_bank_details_pkey" PRIMARY KEY ("source_record_id"),
    CONSTRAINT "source_record_bank_details_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "source_record_bank_details_bank_account_fkey" FOREIGN KEY ("bank_account_id")
        REFERENCES "legal"."bank_account"("bank_account_id") ON UPDATE CASCADE ON DELETE SET NULL
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "source_record_bank_details_account_operation_idx"
    ON "legal"."source_record_bank_details" ("bank_account_id", "external_operation_id")
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_record_document_details" (
    "source_record_id" bigint NOT NULL,
    "source_document_type" varchar(100),
    "source_direction" varchar(100),
    "source_status" varchar(100),
    "document_number" varchar(255),
    "document_date" date,
    "external_document_id" text,
    "external_document_type" varchar(100),
    "external_status" varchar(100),
    "processed_at" timestamp without time zone,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_record_document_details_pkey" PRIMARY KEY ("source_record_id"),
    CONSTRAINT "source_record_document_details_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "source_record_document_details_number_date_idx"
    ON "legal"."source_record_document_details" ("document_date", "document_number")
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."source_record_vat_book_details" (
    "source_record_id" bigint NOT NULL,
    "vat_book_import_id" bigint,
    "vat_book_entry_id" bigint,
    "legal_id" varchar(12),
    "book_type" varchar(20),
    "year" smallint,
    "quarter" smallint,
    "row_number" integer,
    "operation_code" varchar(20),
    "invoice_number" varchar(255),
    "invoice_date" date,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "source_record_vat_book_details_pkey" PRIMARY KEY ("source_record_id"),
    CONSTRAINT "source_record_vat_book_details_book_type_check" CHECK ("book_type" IS NULL OR "book_type" IN ('purchase', 'sales')),
    CONSTRAINT "source_record_vat_book_details_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "source_record_vat_book_details_import_fkey" FOREIGN KEY ("vat_book_import_id")
        REFERENCES "legal"."vat_book_imports"("vat_book_import_id") ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT "source_record_vat_book_details_entry_fkey" FOREIGN KEY ("vat_book_entry_id")
        REFERENCES "legal"."vat_book_entries"("vat_book_entry_id") ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT "source_record_vat_book_details_legal_fkey" FOREIGN KEY ("legal_id")
        REFERENCES "legal"."legal"("legal_id") ON UPDATE CASCADE ON DELETE SET NULL
)
SQL);

        DB::statement(<<<'SQL'
CREATE UNIQUE INDEX IF NOT EXISTS "source_record_vat_book_details_entry_unique"
    ON "legal"."source_record_vat_book_details" ("vat_book_entry_id")
    WHERE "vat_book_entry_id" IS NOT NULL
SQL);

        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS "legal"."document_sources" (
    "document_source_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "document_id" bigint NOT NULL,
    "source_record_id" bigint NOT NULL,
    "source_item_key" varchar(255) DEFAULT '' NOT NULL,
    "source_role" varchar(100) DEFAULT 'evidence' NOT NULL,
    "confidence" numeric(5, 4),
    "matched_by" varchar(100),
    "matched_at" timestamp without time zone,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "document_sources_pkey" PRIMARY KEY ("document_source_id"),
    CONSTRAINT "document_sources_source_role_not_empty_check" CHECK (btrim("source_role") <> ''),
    CONSTRAINT "document_sources_confidence_check" CHECK ("confidence" IS NULL OR ("confidence" >= 0 AND "confidence" <= 1)),
    CONSTRAINT "document_sources_document_source_item_key" UNIQUE ("document_id", "source_record_id", "source_item_key"),
    CONSTRAINT "document_sources_source_item_unique" UNIQUE ("source_record_id", "source_item_key"),
    CONSTRAINT "document_sources_document_fkey" FOREIGN KEY ("document_id")
        REFERENCES "legal"."documents"("document_id") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "document_sources_source_record_fkey" FOREIGN KEY ("source_record_id")
        REFERENCES "legal"."source_records"("source_record_id") ON UPDATE CASCADE ON DELETE CASCADE
)
SQL);

        DB::statement(<<<'SQL'
CREATE INDEX IF NOT EXISTS "document_sources_document_idx"
    ON "legal"."document_sources" ("document_id")
SQL);
    }

    public function down(): void
    {
        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."document_sources" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_record_vat_book_details" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_record_document_details" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_record_bank_details" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_record_product_marks" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_record_files" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_record_amounts" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_record_parties" CASCADE
SQL);

        DB::statement(<<<'SQL'
DROP TABLE IF EXISTS "legal"."source_records" CASCADE
SQL);
    }
};
