--
-- PostgreSQL database dump
--

\restrict LGPbGUm0hTURiqU5b09EA6MGgidNQ7dlKAhxabrT6Tiw46uAFwJ1kesqfyS7Von

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: legal; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA legal;


--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: bank_transaction_1c_set_hash(); Type: FUNCTION; Schema: legal; Owner: -
--

CREATE FUNCTION legal.bank_transaction_1c_set_hash() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.transaction_hash := md5(CONCAT(NEW."1c_bank_id", '-', NEW."1c_account_number", '-', NEW.operation_id));
  RETURN NEW;
END;
$$;


--
-- Name: legal_kudir_record_set_year(); Type: FUNCTION; Schema: legal; Owner: -
--

CREATE FUNCTION legal.legal_kudir_record_set_year() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.year := EXTRACT(YEAR FROM NEW.date)::integer;
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accountant_report_link_types; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.accountant_report_link_types (
    accountant_report_link_type_id bigint CONSTRAINT accountant_report_link_type_accountant_report_link_typ_not_null NOT NULL,
    alias character varying(100) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT accountant_report_link_types_alias_not_empty_check CHECK ((btrim((alias)::text) <> ''::text))
);


--
-- Name: accountant_report_link_types_accountant_report_link_type_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.accountant_report_link_types ALTER COLUMN accountant_report_link_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.accountant_report_link_types_accountant_report_link_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accountant_report_links; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.accountant_report_links (
    accountant_report_link_id bigint NOT NULL,
    accountant_report_link_type_id bigint NOT NULL,
    vat_book_entry_id bigint NOT NULL,
    document_bank_transaction_id bigint NOT NULL,
    amount numeric(18,2) NOT NULL,
    vat_amount numeric(18,2),
    currency character(3) DEFAULT 'RUB'::bpchar NOT NULL,
    matched_on date,
    confidence numeric(5,4),
    source character varying(50) DEFAULT 'manual'::character varying NOT NULL,
    algorithm character varying(100),
    notes text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT accountant_report_links_amount_non_negative_check CHECK ((amount >= (0)::numeric)),
    CONSTRAINT accountant_report_links_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)))),
    CONSTRAINT accountant_report_links_source_check CHECK (((source)::text = ANY ((ARRAY['manual'::character varying, 'algorithm'::character varying, 'import'::character varying])::text[]))),
    CONSTRAINT accountant_report_links_vat_amount_non_negative_check CHECK (((vat_amount IS NULL) OR (vat_amount >= (0)::numeric)))
);


--
-- Name: accountant_report_links_accountant_report_link_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.accountant_report_links ALTER COLUMN accountant_report_link_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.accountant_report_links_accountant_report_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_credentials; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.api_credentials (
    api_credential_id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    credential_type character varying(100) NOT NULL,
    owner_type character varying(100),
    owner_id character varying(100),
    name character varying(255),
    encrypted_secret text NOT NULL,
    meta jsonb,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    last_used_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


--
-- Name: api_credentials_api_credential_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.api_credentials ALTER COLUMN api_credential_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.api_credentials_api_credential_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_sync_requests; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.api_sync_requests (
    api_sync_request_id bigint NOT NULL,
    api_sync_run_id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    method character varying(10) NOT NULL,
    endpoint character varying(255) NOT NULL,
    url text NOT NULL,
    params jsonb,
    http_status integer,
    duration_ms integer,
    response_hash character(64),
    response_json jsonb,
    error text,
    requested_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    response_body text
);


--
-- Name: api_sync_requests_api_sync_request_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.api_sync_requests ALTER COLUMN api_sync_request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.api_sync_requests_api_sync_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_sync_runs; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.api_sync_runs (
    api_sync_run_id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    type character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'started'::character varying NOT NULL,
    period_from date,
    period_till date,
    accounts_count integer DEFAULT 0 NOT NULL,
    operations_count integer DEFAULT 0 NOT NULL,
    requests_count integer DEFAULT 0 NOT NULL,
    error text,
    started_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


--
-- Name: api_sync_runs_api_sync_run_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.api_sync_runs ALTER COLUMN api_sync_run_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.api_sync_runs_api_sync_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.bank (
    bank_id character(9) NOT NULL,
    bank_name character varying(500) NOT NULL,
    api_provider_id bigint
);


--
-- Name: bank_account; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.bank_account (
    account_number character(20) NOT NULL,
    bank_id character(9) NOT NULL,
    legal_id character varying(12) NOT NULL,
    name character varying(300) NOT NULL,
    currency character varying(50) NOT NULL,
    account_type character varying(100) NOT NULL,
    activation_date date,
    balance_otb numeric(10,2),
    balance_authorized numeric(10,2),
    balance_pending_payments numeric(10,2),
    balance_pending_requisitions numeric(10,2),
    bank_account_id bigint NOT NULL
);


--
-- Name: bank_account_bank_account_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

CREATE SEQUENCE legal.bank_account_bank_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bank_account_bank_account_id_seq; Type: SEQUENCE OWNED BY; Schema: legal; Owner: -
--

ALTER SEQUENCE legal.bank_account_bank_account_id_seq OWNED BY legal.bank_account.bank_account_id;


--
-- Name: counterparty_opening_balances; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.counterparty_opening_balances (
    counterparty_opening_balance_id bigint CONSTRAINT counterparty_opening_balanc_counterparty_opening_balan_not_null NOT NULL,
    legal_id character varying(12) NOT NULL,
    contractor_inn character varying(12) NOT NULL,
    starts_on date NOT NULL,
    amount numeric(18,2) NOT NULL,
    source character varying(255),
    comment text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT counterparty_opening_balances_contractor_inn_not_empty_check CHECK ((btrim((contractor_inn)::text) <> ''::text))
);


--
-- Name: counterparty_opening_balances_counterparty_opening_balance__seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.counterparty_opening_balances ALTER COLUMN counterparty_opening_balance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.counterparty_opening_balances_counterparty_opening_balance__seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_bank_transaction; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.document_bank_transaction (
    document_bank_transaction_id bigint NOT NULL,
    document_id bigint NOT NULL,
    bank_account_id bigint NOT NULL,
    bank_id character(9) NOT NULL,
    account_number character(20) NOT NULL,
    external_operation_id character varying(100) NOT NULL,
    external_id character varying(100),
    operation_date date,
    draw_date date,
    charge_date date,
    order_intraday character varying(100),
    amount numeric(18,2),
    signed_amount numeric(18,2),
    currency character(3),
    payer_name character varying(1000),
    payer_inn character varying(12),
    payer_kpp character varying(9),
    payer_account character(20),
    payer_bic character(9),
    payer_bank character varying(500),
    payer_corr_account character(20),
    recipient_name character varying(1000),
    recipient_inn character varying(12),
    recipient_kpp character varying(9),
    recipient_account character(20),
    recipient_bic character(9),
    recipient_bank character varying(500),
    recipient_corr_account character(20),
    payment_purpose character varying(4000),
    payment_type character varying(100),
    operation_type character varying(100),
    uin character varying(100),
    creator_status character varying(100),
    kbk character varying(100),
    oktmo character varying(100),
    tax_evidence character varying(100),
    tax_period character varying(100),
    tax_doc_number character varying(100),
    tax_doc_date character varying(100),
    tax_type character varying(100),
    execution_order character varying(5),
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT document_bank_transaction_operation_id_not_empty_check CHECK ((btrim((external_operation_id)::text) <> ''::text))
);


--
-- Name: document_bank_transaction_document_bank_transaction_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.document_bank_transaction ALTER COLUMN document_bank_transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.document_bank_transaction_document_bank_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_parties; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.document_parties (
    document_party_id bigint NOT NULL,
    document_id bigint NOT NULL,
    party_id bigint,
    role_index smallint DEFAULT 1 NOT NULL,
    name_snapshot character varying(1000) NOT NULL,
    inn_snapshot character varying(12),
    kpp_snapshot character varying(9),
    country_code character(2) DEFAULT 'RU'::bpchar NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    document_party_role_id smallint NOT NULL,
    CONSTRAINT document_parties_name_snapshot_not_empty_check CHECK ((btrim((name_snapshot)::text) <> ''::text))
);


--
-- Name: document_parties_document_party_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.document_parties ALTER COLUMN document_party_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.document_parties_document_party_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_party_roles; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.document_party_roles (
    document_party_role_id smallint NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    document_group character varying(100),
    is_system boolean DEFAULT true NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    sort_order smallint DEFAULT 100 NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT document_party_roles_code_not_empty_check CHECK ((btrim((code)::text) <> ''::text)),
    CONSTRAINT document_party_roles_name_not_empty_check CHECK ((btrim((name)::text) <> ''::text))
);


--
-- Name: document_party_roles_document_party_role_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.document_party_roles ALTER COLUMN document_party_role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.document_party_roles_document_party_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_sources; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.document_sources (
    document_source_id bigint NOT NULL,
    document_id bigint NOT NULL,
    source_record_id bigint NOT NULL,
    source_item_key character varying(255) DEFAULT ''::character varying NOT NULL,
    source_role character varying(100) DEFAULT 'evidence'::character varying NOT NULL,
    confidence numeric(5,4),
    matched_by character varying(100),
    matched_at timestamp without time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT document_sources_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)))),
    CONSTRAINT document_sources_source_role_not_empty_check CHECK ((btrim((source_role)::text) <> ''::text))
);


--
-- Name: document_sources_document_source_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.document_sources ALTER COLUMN document_source_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.document_sources_document_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_types; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.document_types (
    document_type_id smallint NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    document_group text NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    is_tax_document boolean DEFAULT false NOT NULL,
    is_money_document boolean DEFAULT false NOT NULL,
    is_inventory_document boolean DEFAULT false NOT NULL,
    is_contract_document boolean DEFAULT false NOT NULL,
    creates_accounting_events boolean DEFAULT false NOT NULL,
    creates_management_events boolean DEFAULT false NOT NULL,
    creates_tax_events boolean DEFAULT false NOT NULL,
    requires_parties boolean DEFAULT true NOT NULL,
    requires_lines boolean DEFAULT false NOT NULL,
    supports_corrections boolean DEFAULT false NOT NULL,
    supports_files boolean DEFAULT true NOT NULL,
    default_direction text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: document_types_document_type_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.document_types ALTER COLUMN document_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.document_types_document_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.documents (
    document_id bigint NOT NULL,
    document_type_id smallint NOT NULL,
    document_date date,
    document_number text,
    title text,
    amount numeric(18,2),
    currency character(3),
    status text DEFAULT 'imported'::text NOT NULL,
    source_system text,
    external_id text,
    external_hash text,
    source_api_sync_request_id bigint,
    source_file_id bigint,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    imported_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT now() NOT NULL,
    CONSTRAINT documents_external_hash_not_empty_check CHECK (((external_hash IS NULL) OR (btrim(external_hash) <> ''::text))),
    CONSTRAINT documents_external_id_not_empty_check CHECK (((external_id IS NULL) OR (btrim(external_id) <> ''::text))),
    CONSTRAINT documents_source_system_not_empty_check CHECK (((source_system IS NULL) OR (btrim(source_system) <> ''::text))),
    CONSTRAINT documents_status_not_empty_check CHECK ((btrim(status) <> ''::text))
);


--
-- Name: documents_document_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.documents ALTER COLUMN document_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.documents_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laravel_failed_jobs; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_failed_jobs (
    id bigint CONSTRAINT failed_jobs_id_not_null NOT NULL,
    uuid character varying(255) CONSTRAINT failed_jobs_uuid_not_null NOT NULL,
    connection character varying(255) CONSTRAINT failed_jobs_connection_not_null NOT NULL,
    queue character varying(255) CONSTRAINT failed_jobs_queue_not_null NOT NULL,
    payload text CONSTRAINT failed_jobs_payload_not_null NOT NULL,
    exception text CONSTRAINT failed_jobs_exception_not_null NOT NULL,
    failed_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT failed_jobs_failed_at_not_null NOT NULL
);


--
-- Name: failed_jobs_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

CREATE SEQUENCE legal.failed_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: failed_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: legal; Owner: -
--

ALTER SEQUENCE legal.failed_jobs_id_seq OWNED BY legal.laravel_failed_jobs.id;


--
-- Name: import_runs; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.import_runs (
    import_run_id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    type character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'started'::character varying NOT NULL,
    source_file_name character varying(500),
    file_sha256 character(64),
    file_size bigint,
    records_count integer DEFAULT 0 NOT NULL,
    operations_count integer DEFAULT 0 NOT NULL,
    error text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    started_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT import_runs_provider_not_empty_check CHECK ((btrim((provider)::text) <> ''::text)),
    CONSTRAINT import_runs_status_not_empty_check CHECK ((btrim((status)::text) <> ''::text)),
    CONSTRAINT import_runs_type_not_empty_check CHECK ((btrim((type)::text) <> ''::text))
);


--
-- Name: import_runs_import_run_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.import_runs ALTER COLUMN import_run_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.import_runs_import_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laravel_jobs; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_jobs (
    id bigint CONSTRAINT jobs_id_not_null NOT NULL,
    queue character varying(255) CONSTRAINT jobs_queue_not_null NOT NULL,
    payload text CONSTRAINT jobs_payload_not_null NOT NULL,
    attempts smallint CONSTRAINT jobs_attempts_not_null NOT NULL,
    reserved_at integer,
    available_at integer CONSTRAINT jobs_available_at_not_null NOT NULL,
    created_at integer CONSTRAINT jobs_created_at_not_null NOT NULL
);


--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

CREATE SEQUENCE legal.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: legal; Owner: -
--

ALTER SEQUENCE legal.jobs_id_seq OWNED BY legal.laravel_jobs.id;


--
-- Name: kassa; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.kassa (
    kassa_id bigint NOT NULL,
    article_id smallint,
    user_id integer NOT NULL,
    "time" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    amount integer NOT NULL,
    description character varying(2000) NOT NULL,
    reconciliation_id bigint,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: kassa_article; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.kassa_article (
    article_id smallint NOT NULL,
    article character varying(100) NOT NULL
);


--
-- Name: kassa_article_article_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.kassa_article ALTER COLUMN article_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.kassa_article_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kassa_kassa_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.kassa ALTER COLUMN kassa_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.kassa_kassa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laravel_cache; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_cache (
    key character varying(255) CONSTRAINT cache_key_not_null NOT NULL,
    value text CONSTRAINT cache_value_not_null NOT NULL,
    expiration bigint CONSTRAINT cache_expiration_not_null NOT NULL
);


--
-- Name: laravel_cache_locks; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_cache_locks (
    key character varying(255) CONSTRAINT cache_locks_key_not_null NOT NULL,
    owner character varying(255) CONSTRAINT cache_locks_owner_not_null NOT NULL,
    expiration bigint CONSTRAINT cache_locks_expiration_not_null NOT NULL
);


--
-- Name: laravel_job_batches; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_job_batches (
    id character varying(255) CONSTRAINT job_batches_id_not_null NOT NULL,
    name character varying(255) CONSTRAINT job_batches_name_not_null NOT NULL,
    total_jobs integer CONSTRAINT job_batches_total_jobs_not_null NOT NULL,
    pending_jobs integer CONSTRAINT job_batches_pending_jobs_not_null NOT NULL,
    failed_jobs integer CONSTRAINT job_batches_failed_jobs_not_null NOT NULL,
    failed_job_ids text CONSTRAINT job_batches_failed_job_ids_not_null NOT NULL,
    options text,
    cancelled_at integer,
    created_at integer CONSTRAINT job_batches_created_at_not_null NOT NULL,
    finished_at integer
);


--
-- Name: laravel_migrations; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_migrations (
    id integer CONSTRAINT migrations_id_not_null NOT NULL,
    migration character varying(255) CONSTRAINT migrations_migration_not_null NOT NULL,
    batch integer CONSTRAINT migrations_batch_not_null NOT NULL
);


--
-- Name: laravel_password_reset_tokens; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_password_reset_tokens (
    email character varying(255) CONSTRAINT password_reset_tokens_email_not_null NOT NULL,
    token character varying(255) CONSTRAINT password_reset_tokens_token_not_null NOT NULL,
    created_at timestamp(0) without time zone
);


--
-- Name: laravel_sessions; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_sessions (
    id character varying(255) CONSTRAINT sessions_id_not_null NOT NULL,
    user_id bigint,
    ip_address character varying(45),
    user_agent text,
    payload text CONSTRAINT sessions_payload_not_null NOT NULL,
    last_activity integer CONSTRAINT sessions_last_activity_not_null NOT NULL
);


--
-- Name: laravel_users; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.laravel_users (
    id bigint CONSTRAINT users_id_not_null NOT NULL,
    name character varying(255) CONSTRAINT users_name_not_null NOT NULL,
    email character varying(255) CONSTRAINT users_email_not_null NOT NULL,
    email_verified_at timestamp(0) without time zone,
    password character varying(255),
    remember_token character varying(100),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    google_id character varying(255),
    avatar character varying(255),
    role character varying(255) DEFAULT 'admin'::character varying CONSTRAINT users_role_not_null NOT NULL,
    is_active boolean DEFAULT true CONSTRAINT users_is_active_not_null NOT NULL,
    last_login_at timestamp(0) without time zone
);


--
-- Name: legal_brand; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.legal_brand (
    brand_id bigint NOT NULL,
    legal_id_owner character varying(12),
    brand character varying(200) NOT NULL,
    comment character varying(3000)
);


--
-- Name: legal_brand_brand_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.legal_brand ALTER COLUMN brand_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.legal_brand_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: legal_own; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.legal_own (
    legal_id character varying(12) CONSTRAINT legal_legal_id_not_null NOT NULL,
    legal_name character varying(500) CONSTRAINT legal_legal_name_not_null NOT NULL,
    legal_fullname character varying(500) CONSTRAINT legal_legal_fullname_not_null NOT NULL,
    legal_letter character(1) CONSTRAINT legal_legal_letter_not_null NOT NULL,
    firstname character varying(200) CONSTRAINT legal_firstname_not_null NOT NULL,
    lastname character varying(200) CONSTRAINT legal_lastname_not_null NOT NULL,
    middlename character varying(200) CONSTRAINT legal_middlename_not_null NOT NULL,
    legal_color character varying(30) CONSTRAINT legal_legal_color_not_null NOT NULL,
    tax_system text CONSTRAINT legal_tax_system_not_null NOT NULL,
    tax_rate numeric(10,2) CONSTRAINT legal_tax_rate_not_null NOT NULL,
    vat_rate smallint,
    legal_inn character varying(12) CONSTRAINT legal_legal_inn_not_null NOT NULL,
    legal_ogrn bigint CONSTRAINT legal_legal_ogrn_not_null NOT NULL,
    legal_comment text,
    addr_index bigint,
    addr_region_code character varying(3),
    addr_region character varying(500),
    addr_town character varying(500),
    addr_street character varying(500),
    addr_house character varying(50),
    addr_flat character varying(50),
    suz_conn_id character(36),
    suz_oms_id character(36),
    cert_cn character varying(500),
    edo_light_id character varying(100),
    cdek_client_id character varying(500),
    cdek_client_secret character varying(500),
    cdek_token character varying(3000),
    cdek_token_expired timestamp without time zone,
    dellin_session_id character(36),
    tax_periods jsonb DEFAULT '{}'::jsonb CONSTRAINT legal_tax_periods_not_null NOT NULL
);


--
-- Name: legal_tax; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.legal_tax (
    legal_id character varying(12) NOT NULL,
    year integer DEFAULT 0 NOT NULL,
    quarter text NOT NULL,
    income numeric(10,2),
    cost numeric(10,2),
    income_declaration numeric(10,2),
    cost_declaration numeric(10,2),
    base_declaration numeric(10,2),
    description character varying(2000)
);


--
-- Name: legal_tax_period; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.legal_tax_period (
    legal_id character varying(12) NOT NULL,
    year integer NOT NULL,
    tax_system text NOT NULL,
    usn_doh numeric(10,2) NOT NULL,
    usn_doh_ras numeric(10,2) NOT NULL,
    vat_20 integer DEFAULT 0,
    vat_5 integer DEFAULT 0 NOT NULL
);


--
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

CREATE SEQUENCE legal.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: legal; Owner: -
--

ALTER SEQUENCE legal.migrations_id_seq OWNED BY legal.laravel_migrations.id;


--
-- Name: money_edges; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.money_edges (
    money_edge_id bigint NOT NULL,
    source_document_id bigint NOT NULL,
    source_document_bank_transaction_id bigint NOT NULL,
    payer_document_party_id bigint,
    recipient_document_party_id bigint,
    occurred_on date,
    amount numeric(18,2) NOT NULL,
    currency character(3) DEFAULT 'RUB'::bpchar NOT NULL,
    payer_name_snapshot character varying(1000),
    payer_inn_snapshot character varying(12),
    recipient_name_snapshot character varying(1000),
    recipient_inn_snapshot character varying(12),
    payment_purpose character varying(4000),
    algorithm character varying(100) DEFAULT 'bank_operation_v1'::character varying NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT money_edges_amount_positive_check CHECK ((amount >= (0)::numeric))
);


--
-- Name: money_edges_money_edge_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.money_edges ALTER COLUMN money_edge_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.money_edges_money_edge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_record_amounts; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_record_amounts (
    source_record_amount_id bigint NOT NULL,
    source_record_id bigint NOT NULL,
    amount_type character varying(100) NOT NULL,
    amount numeric(18,2) NOT NULL,
    currency character(3) DEFAULT 'RUB'::bpchar NOT NULL,
    tax_rate numeric(8,4),
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT source_record_amounts_type_not_empty_check CHECK ((btrim((amount_type)::text) <> ''::text))
);


--
-- Name: source_record_amounts_source_record_amount_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.source_record_amounts ALTER COLUMN source_record_amount_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.source_record_amounts_source_record_amount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_record_bank_details; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_record_bank_details (
    source_record_id bigint NOT NULL,
    bank_account_id bigint,
    bank_id character(9),
    account_number character(20),
    external_operation_id character varying(100),
    operation_date date,
    draw_date date,
    charge_date date,
    order_intraday character varying(100),
    payment_purpose character varying(4000),
    payment_type character varying(100),
    operation_type character varying(100),
    signed_amount numeric(18,2),
    saldo numeric(18,2),
    tax_fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: source_record_document_details; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_record_document_details (
    source_record_id bigint NOT NULL,
    source_document_type character varying(100),
    source_direction character varying(100),
    source_status character varying(100),
    document_number character varying(255),
    document_date date,
    external_document_id text,
    external_document_type character varying(100),
    external_status character varying(100),
    processed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: source_record_files; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_record_files (
    source_record_file_id bigint NOT NULL,
    source_record_id bigint NOT NULL,
    file_role character varying(100) NOT NULL,
    source_file_name character varying(500),
    stored_path character varying(1000) NOT NULL,
    mime_type character varying(255),
    file_sha256 character(64),
    file_size bigint,
    encoding character varying(100),
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT source_record_files_role_not_empty_check CHECK ((btrim((file_role)::text) <> ''::text)),
    CONSTRAINT source_record_files_stored_path_not_empty_check CHECK ((btrim((stored_path)::text) <> ''::text))
);


--
-- Name: source_record_files_source_record_file_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.source_record_files ALTER COLUMN source_record_file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.source_record_files_source_record_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_record_parties; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_record_parties (
    source_record_party_id bigint NOT NULL,
    source_record_id bigint NOT NULL,
    source_party_role character varying(100) NOT NULL,
    role_index smallint DEFAULT 1 NOT NULL,
    party_name character varying(1000),
    inn character varying(12),
    kpp character varying(20),
    account_number character varying(34),
    bank_bic character varying(20),
    bank_name character varying(500),
    address text,
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT source_record_parties_role_not_empty_check CHECK ((btrim((source_party_role)::text) <> ''::text))
);


--
-- Name: source_record_parties_source_record_party_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.source_record_parties ALTER COLUMN source_record_party_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.source_record_parties_source_record_party_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_record_product_marks; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_record_product_marks (
    source_record_product_mark_id bigint CONSTRAINT source_record_product_marks_source_record_product_mark_not_null NOT NULL,
    source_record_id bigint NOT NULL,
    mark_code text NOT NULL,
    mark_type character varying(100),
    product_group character varying(100),
    gtin character varying(14),
    serial_number text,
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT source_record_product_marks_code_not_empty_check CHECK ((btrim(mark_code) <> ''::text))
);


--
-- Name: source_record_product_marks_source_record_product_mark_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.source_record_product_marks ALTER COLUMN source_record_product_mark_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.source_record_product_marks_source_record_product_mark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_record_vat_book_details; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_record_vat_book_details (
    source_record_id bigint NOT NULL,
    vat_book_import_id bigint,
    vat_book_entry_id bigint,
    legal_id character varying(12),
    book_type character varying(20),
    year smallint,
    quarter smallint,
    row_number integer,
    operation_code character varying(20),
    invoice_number character varying(255),
    invoice_date date,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT source_record_vat_book_details_book_type_check CHECK (((book_type IS NULL) OR ((book_type)::text = ANY ((ARRAY['purchase'::character varying, 'sales'::character varying])::text[]))))
);


--
-- Name: source_records; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.source_records (
    source_record_id bigint NOT NULL,
    source_system character varying(100) NOT NULL,
    source_channel character varying(100),
    source_record_type character varying(100) NOT NULL,
    external_id text,
    external_hash character(64),
    source_api_sync_request_id bigint,
    source_vat_book_entry_id bigint,
    source_file_path character varying(1000),
    received_at timestamp without time zone,
    recorded_at timestamp without time zone,
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT source_records_external_hash_not_empty_check CHECK (((external_hash IS NULL) OR (btrim((external_hash)::text) <> ''::text))),
    CONSTRAINT source_records_external_id_not_empty_check CHECK (((external_id IS NULL) OR (btrim(external_id) <> ''::text))),
    CONSTRAINT source_records_source_record_type_not_empty_check CHECK ((btrim((source_record_type)::text) <> ''::text)),
    CONSTRAINT source_records_source_system_not_empty_check CHECK ((btrim((source_system)::text) <> ''::text))
);


--
-- Name: source_records_source_record_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.source_records ALTER COLUMN source_record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.source_records_source_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploaded_files; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.uploaded_files (
    uploaded_file_id bigint NOT NULL,
    import_run_id bigint,
    provider character varying(50) NOT NULL,
    file_role character varying(100) DEFAULT 'source'::character varying NOT NULL,
    source_file_name character varying(500) NOT NULL,
    stored_path character varying(1000) NOT NULL,
    mime_type character varying(255),
    file_sha256 character(64) NOT NULL,
    file_size bigint NOT NULL,
    uploaded_by_user_id bigint,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    uploaded_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT uploaded_files_file_role_not_empty_check CHECK ((btrim((file_role)::text) <> ''::text)),
    CONSTRAINT uploaded_files_file_sha256_not_empty_check CHECK ((btrim((file_sha256)::text) <> ''::text)),
    CONSTRAINT uploaded_files_provider_not_empty_check CHECK ((btrim((provider)::text) <> ''::text)),
    CONSTRAINT uploaded_files_source_file_name_not_empty_check CHECK ((btrim((source_file_name)::text) <> ''::text)),
    CONSTRAINT uploaded_files_stored_path_not_empty_check CHECK ((btrim((stored_path)::text) <> ''::text))
);


--
-- Name: uploaded_files_uploaded_file_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.uploaded_files ALTER COLUMN uploaded_file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.uploaded_files_uploaded_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

CREATE SEQUENCE legal.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: legal; Owner: -
--

ALTER SEQUENCE legal.users_id_seq OWNED BY legal.laravel_users.id;


--
-- Name: vat_book_entries; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.vat_book_entries (
    vat_book_entry_id bigint NOT NULL,
    vat_book_import_id bigint NOT NULL,
    legal_id character varying(12) NOT NULL,
    book_type character varying(20) NOT NULL,
    year smallint NOT NULL,
    quarter smallint NOT NULL,
    period_code smallint NOT NULL,
    row_number integer NOT NULL,
    operation_code character varying(20),
    invoice_number character varying(255),
    invoice_date date,
    correction_invoice_number character varying(255),
    correction_invoice_date date,
    acceptance_date date,
    payment_doc_number character varying(255),
    payment_doc_date date,
    contractor_name character varying(1000),
    contractor_inn character varying(12),
    contractor_kpp character varying(20),
    currency_code character varying(10),
    amount_total numeric(18,2),
    amount_without_vat numeric(18,2),
    vat_amount numeric(18,2),
    raw_entry jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT vat_book_entries_book_type_check CHECK (((book_type)::text = ANY ((ARRAY['purchase'::character varying, 'sales'::character varying])::text[])))
);


--
-- Name: vat_book_entries_vat_book_entry_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.vat_book_entries ALTER COLUMN vat_book_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.vat_book_entries_vat_book_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vat_book_imports; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.vat_book_imports (
    vat_book_import_id bigint NOT NULL,
    legal_id character varying(12) NOT NULL,
    book_type character varying(20) NOT NULL,
    year smallint NOT NULL,
    quarter smallint NOT NULL,
    period_code smallint NOT NULL,
    knd character varying(20),
    file_identifier character varying(255),
    source_file_name character varying(500) NOT NULL,
    stored_path character varying(1000) NOT NULL,
    file_sha256 character(64) NOT NULL,
    file_size bigint NOT NULL,
    xml_version character varying(20),
    program_version character varying(255),
    total_amount numeric(18,2),
    total_amount_without_vat numeric(18,2),
    total_vat_amount numeric(18,2),
    entries_count integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    imported_at timestamp without time zone DEFAULT now() NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT vat_book_imports_book_type_check CHECK (((book_type)::text = ANY ((ARRAY['purchase'::character varying, 'sales'::character varying])::text[]))),
    CONSTRAINT vat_book_imports_quarter_check CHECK (((quarter >= 1) AND (quarter <= 4)))
);


--
-- Name: vat_book_imports_vat_book_import_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.vat_book_imports ALTER COLUMN vat_book_import_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.vat_book_imports_vat_book_import_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vat_events; Type: TABLE; Schema: legal; Owner: -
--

CREATE TABLE legal.vat_events (
    vat_event_id bigint NOT NULL,
    source_system character varying(100) DEFAULT 'accountant_vat_book'::character varying NOT NULL,
    source_vat_book_import_id bigint,
    source_vat_book_entry_id bigint,
    legal_id character varying(12) NOT NULL,
    year smallint NOT NULL,
    quarter smallint NOT NULL,
    book_type character varying(20) NOT NULL,
    vat_direction character varying(20) NOT NULL,
    occurred_on date,
    invoice_number character varying(255),
    invoice_date date,
    contractor_name character varying(1000),
    contractor_inn character varying(12),
    contractor_kpp character varying(20),
    amount_total numeric(18,2),
    amount_without_vat numeric(18,2),
    vat_amount numeric(18,2) NOT NULL,
    signed_vat_amount numeric(18,2) NOT NULL,
    operation_code character varying(20),
    algorithm character varying(100) DEFAULT 'accountant_vat_book_v1'::character varying NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    source_document_id bigint,
    source_document_bank_transaction_id bigint,
    CONSTRAINT vat_events_book_type_check CHECK (((book_type)::text = ANY ((ARRAY['purchase'::character varying, 'sales'::character varying])::text[]))),
    CONSTRAINT vat_events_vat_direction_check CHECK (((vat_direction)::text = ANY ((ARRAY['input'::character varying, 'output'::character varying])::text[])))
);


--
-- Name: vat_events_vat_event_id_seq; Type: SEQUENCE; Schema: legal; Owner: -
--

ALTER TABLE legal.vat_events ALTER COLUMN vat_event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME legal.vat_events_vat_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_account bank_account_id; Type: DEFAULT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.bank_account ALTER COLUMN bank_account_id SET DEFAULT nextval('legal.bank_account_bank_account_id_seq'::regclass);


--
-- Name: laravel_failed_jobs id; Type: DEFAULT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_failed_jobs ALTER COLUMN id SET DEFAULT nextval('legal.failed_jobs_id_seq'::regclass);


--
-- Name: laravel_jobs id; Type: DEFAULT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_jobs ALTER COLUMN id SET DEFAULT nextval('legal.jobs_id_seq'::regclass);


--
-- Name: laravel_migrations id; Type: DEFAULT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_migrations ALTER COLUMN id SET DEFAULT nextval('legal.migrations_id_seq'::regclass);


--
-- Name: laravel_users id; Type: DEFAULT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_users ALTER COLUMN id SET DEFAULT nextval('legal.users_id_seq'::regclass);


--
-- Name: accountant_report_link_types accountant_report_link_types_alias_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.accountant_report_link_types
    ADD CONSTRAINT accountant_report_link_types_alias_key UNIQUE (alias);


--
-- Name: accountant_report_link_types accountant_report_link_types_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.accountant_report_link_types
    ADD CONSTRAINT accountant_report_link_types_pkey PRIMARY KEY (accountant_report_link_type_id);


--
-- Name: accountant_report_links accountant_report_links_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.accountant_report_links
    ADD CONSTRAINT accountant_report_links_pkey PRIMARY KEY (accountant_report_link_id);


--
-- Name: api_credentials api_credentials_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.api_credentials
    ADD CONSTRAINT api_credentials_pkey PRIMARY KEY (api_credential_id);


--
-- Name: api_sync_requests api_sync_requests_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.api_sync_requests
    ADD CONSTRAINT api_sync_requests_pkey PRIMARY KEY (api_sync_request_id);


--
-- Name: api_sync_runs api_sync_runs_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.api_sync_runs
    ADD CONSTRAINT api_sync_runs_pkey PRIMARY KEY (api_sync_run_id);


--
-- Name: bank_account bank_account_account_number_bank_id_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.bank_account
    ADD CONSTRAINT bank_account_account_number_bank_id_key UNIQUE (account_number, bank_id);


--
-- Name: bank_account bank_account_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.bank_account
    ADD CONSTRAINT bank_account_pkey PRIMARY KEY (bank_account_id);


--
-- Name: bank bank_api_provider_id_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.bank
    ADD CONSTRAINT bank_api_provider_id_key UNIQUE (api_provider_id);


--
-- Name: bank bank_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.bank
    ADD CONSTRAINT bank_pkey PRIMARY KEY (bank_id);


--
-- Name: laravel_cache_locks cache_locks_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_cache_locks
    ADD CONSTRAINT cache_locks_pkey PRIMARY KEY (key);


--
-- Name: laravel_cache cache_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_cache
    ADD CONSTRAINT cache_pkey PRIMARY KEY (key);


--
-- Name: counterparty_opening_balances counterparty_opening_balances_legal_contractor_start_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.counterparty_opening_balances
    ADD CONSTRAINT counterparty_opening_balances_legal_contractor_start_key UNIQUE (legal_id, contractor_inn, starts_on);


--
-- Name: counterparty_opening_balances counterparty_opening_balances_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.counterparty_opening_balances
    ADD CONSTRAINT counterparty_opening_balances_pkey PRIMARY KEY (counterparty_opening_balance_id);


--
-- Name: document_bank_transaction document_bank_transaction_account_operation_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_bank_transaction
    ADD CONSTRAINT document_bank_transaction_account_operation_key UNIQUE (bank_account_id, external_operation_id);


--
-- Name: document_bank_transaction document_bank_transaction_document_id_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_bank_transaction
    ADD CONSTRAINT document_bank_transaction_document_id_key UNIQUE (document_id);


--
-- Name: document_bank_transaction document_bank_transaction_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_bank_transaction
    ADD CONSTRAINT document_bank_transaction_pkey PRIMARY KEY (document_bank_transaction_id);


--
-- Name: document_parties document_parties_document_role_id_index_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_parties
    ADD CONSTRAINT document_parties_document_role_id_index_key UNIQUE (document_id, document_party_role_id, role_index);


--
-- Name: document_parties document_parties_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_parties
    ADD CONSTRAINT document_parties_pkey PRIMARY KEY (document_party_id);


--
-- Name: document_party_roles document_party_roles_code_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_party_roles
    ADD CONSTRAINT document_party_roles_code_key UNIQUE (code);


--
-- Name: document_party_roles document_party_roles_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_party_roles
    ADD CONSTRAINT document_party_roles_pkey PRIMARY KEY (document_party_role_id);


--
-- Name: document_sources document_sources_document_source_item_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_sources
    ADD CONSTRAINT document_sources_document_source_item_key UNIQUE (document_id, source_record_id, source_item_key);


--
-- Name: document_sources document_sources_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_sources
    ADD CONSTRAINT document_sources_pkey PRIMARY KEY (document_source_id);


--
-- Name: document_sources document_sources_source_item_unique; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_sources
    ADD CONSTRAINT document_sources_source_item_unique UNIQUE (source_record_id, source_item_key);


--
-- Name: document_types document_types_code_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_types
    ADD CONSTRAINT document_types_code_key UNIQUE (code);


--
-- Name: document_types document_types_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_types
    ADD CONSTRAINT document_types_pkey PRIMARY KEY (document_type_id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (document_id);


--
-- Name: laravel_failed_jobs failed_jobs_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_failed_jobs
    ADD CONSTRAINT failed_jobs_pkey PRIMARY KEY (id);


--
-- Name: laravel_failed_jobs failed_jobs_uuid_unique; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_failed_jobs
    ADD CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid);


--
-- Name: import_runs import_runs_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.import_runs
    ADD CONSTRAINT import_runs_pkey PRIMARY KEY (import_run_id);


--
-- Name: laravel_job_batches job_batches_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_job_batches
    ADD CONSTRAINT job_batches_pkey PRIMARY KEY (id);


--
-- Name: laravel_jobs jobs_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: kassa_article kassa_article_article_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.kassa_article
    ADD CONSTRAINT kassa_article_article_key UNIQUE (article);


--
-- Name: kassa_article kassa_article_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.kassa_article
    ADD CONSTRAINT kassa_article_pkey PRIMARY KEY (article_id);


--
-- Name: kassa kassa_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.kassa
    ADD CONSTRAINT kassa_pkey PRIMARY KEY (kassa_id);


--
-- Name: kassa kassa_reconciliation_id_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.kassa
    ADD CONSTRAINT kassa_reconciliation_id_key UNIQUE (reconciliation_id);


--
-- Name: legal_brand legal_brand_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.legal_brand
    ADD CONSTRAINT legal_brand_pkey PRIMARY KEY (brand_id);


--
-- Name: legal_own legal_own_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.legal_own
    ADD CONSTRAINT legal_own_pkey PRIMARY KEY (legal_id);


--
-- Name: legal_tax_period legal_tax_period_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.legal_tax_period
    ADD CONSTRAINT legal_tax_period_pkey PRIMARY KEY (legal_id, year);


--
-- Name: legal_tax legal_tax_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.legal_tax
    ADD CONSTRAINT legal_tax_pkey PRIMARY KEY (legal_id, year, quarter);


--
-- Name: laravel_migrations migrations_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- Name: money_edges money_edges_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.money_edges
    ADD CONSTRAINT money_edges_pkey PRIMARY KEY (money_edge_id);


--
-- Name: money_edges money_edges_source_bank_transaction_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.money_edges
    ADD CONSTRAINT money_edges_source_bank_transaction_key UNIQUE (source_document_bank_transaction_id);


--
-- Name: laravel_password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email);


--
-- Name: laravel_sessions sessions_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: source_record_amounts source_record_amounts_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_amounts
    ADD CONSTRAINT source_record_amounts_pkey PRIMARY KEY (source_record_amount_id);


--
-- Name: source_record_amounts source_record_amounts_record_type_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_amounts
    ADD CONSTRAINT source_record_amounts_record_type_key UNIQUE (source_record_id, amount_type);


--
-- Name: source_record_bank_details source_record_bank_details_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_bank_details
    ADD CONSTRAINT source_record_bank_details_pkey PRIMARY KEY (source_record_id);


--
-- Name: source_record_document_details source_record_document_details_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_document_details
    ADD CONSTRAINT source_record_document_details_pkey PRIMARY KEY (source_record_id);


--
-- Name: source_record_files source_record_files_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_files
    ADD CONSTRAINT source_record_files_pkey PRIMARY KEY (source_record_file_id);


--
-- Name: source_record_parties source_record_parties_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_parties
    ADD CONSTRAINT source_record_parties_pkey PRIMARY KEY (source_record_party_id);


--
-- Name: source_record_parties source_record_parties_record_role_index_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_parties
    ADD CONSTRAINT source_record_parties_record_role_index_key UNIQUE (source_record_id, source_party_role, role_index);


--
-- Name: source_record_product_marks source_record_product_marks_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_product_marks
    ADD CONSTRAINT source_record_product_marks_pkey PRIMARY KEY (source_record_product_mark_id);


--
-- Name: source_record_product_marks source_record_product_marks_record_code_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_product_marks
    ADD CONSTRAINT source_record_product_marks_record_code_key UNIQUE (source_record_id, mark_code);


--
-- Name: source_record_vat_book_details source_record_vat_book_details_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_vat_book_details
    ADD CONSTRAINT source_record_vat_book_details_pkey PRIMARY KEY (source_record_id);


--
-- Name: source_records source_records_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_records
    ADD CONSTRAINT source_records_pkey PRIMARY KEY (source_record_id);


--
-- Name: uploaded_files uploaded_files_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.uploaded_files
    ADD CONSTRAINT uploaded_files_pkey PRIMARY KEY (uploaded_file_id);


--
-- Name: laravel_users users_email_unique; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: laravel_users users_google_id_unique; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_users
    ADD CONSTRAINT users_google_id_unique UNIQUE (google_id);


--
-- Name: laravel_users users_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.laravel_users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vat_book_entries vat_book_entries_import_row_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_book_entries
    ADD CONSTRAINT vat_book_entries_import_row_key UNIQUE (vat_book_import_id, row_number);


--
-- Name: vat_book_entries vat_book_entries_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_book_entries
    ADD CONSTRAINT vat_book_entries_pkey PRIMARY KEY (vat_book_entry_id);


--
-- Name: vat_book_imports vat_book_imports_file_sha256_key; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_book_imports
    ADD CONSTRAINT vat_book_imports_file_sha256_key UNIQUE (file_sha256);


--
-- Name: vat_book_imports vat_book_imports_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_book_imports
    ADD CONSTRAINT vat_book_imports_pkey PRIMARY KEY (vat_book_import_id);


--
-- Name: vat_events vat_events_pkey; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_events
    ADD CONSTRAINT vat_events_pkey PRIMARY KEY (vat_event_id);


--
-- Name: vat_events vat_events_unique_source_entry; Type: CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_events
    ADD CONSTRAINT vat_events_unique_source_entry UNIQUE (source_system, source_vat_book_entry_id);


--
-- Name: accountant_report_links_bank_transaction_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX accountant_report_links_bank_transaction_idx ON legal.accountant_report_links USING btree (document_bank_transaction_id);


--
-- Name: accountant_report_links_entry_transaction_key; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX accountant_report_links_entry_transaction_key ON legal.accountant_report_links USING btree (vat_book_entry_id, document_bank_transaction_id);


--
-- Name: accountant_report_links_type_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX accountant_report_links_type_idx ON legal.accountant_report_links USING btree (accountant_report_link_type_id);


--
-- Name: accountant_report_links_vat_book_entry_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX accountant_report_links_vat_book_entry_idx ON legal.accountant_report_links USING btree (vat_book_entry_id);


--
-- Name: api_credentials_owner_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX api_credentials_owner_idx ON legal.api_credentials USING btree (owner_type, owner_id);


--
-- Name: api_credentials_provider_status_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX api_credentials_provider_status_idx ON legal.api_credentials USING btree (provider, status);


--
-- Name: api_sync_requests_endpoint_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX api_sync_requests_endpoint_idx ON legal.api_sync_requests USING btree (provider, endpoint, http_status);


--
-- Name: api_sync_requests_run_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX api_sync_requests_run_idx ON legal.api_sync_requests USING btree (api_sync_run_id, requested_at);


--
-- Name: api_sync_runs_provider_status_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX api_sync_runs_provider_status_idx ON legal.api_sync_runs USING btree (provider, status, started_at);


--
-- Name: bank_account_account_number_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX bank_account_account_number_idx ON legal.bank_account USING btree (account_number);


--
-- Name: bank_account_bank_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX bank_account_bank_id_idx ON legal.bank_account USING btree (bank_id);


--
-- Name: bank_account_legal_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX bank_account_legal_id_idx ON legal.bank_account USING btree (legal_id);


--
-- Name: cache_expiration_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX cache_expiration_index ON legal.laravel_cache USING btree (expiration);


--
-- Name: cache_locks_expiration_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX cache_locks_expiration_index ON legal.laravel_cache_locks USING btree (expiration);


--
-- Name: counterparty_opening_balances_contractor_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX counterparty_opening_balances_contractor_idx ON legal.counterparty_opening_balances USING btree (contractor_inn, legal_id, starts_on);


--
-- Name: document_bank_transaction_operation_date_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_bank_transaction_operation_date_idx ON legal.document_bank_transaction USING btree (operation_date);


--
-- Name: document_bank_transaction_payer_inn_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_bank_transaction_payer_inn_idx ON legal.document_bank_transaction USING btree (payer_inn);


--
-- Name: document_bank_transaction_recipient_inn_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_bank_transaction_recipient_inn_idx ON legal.document_bank_transaction USING btree (recipient_inn);


--
-- Name: document_parties_document_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_parties_document_id_idx ON legal.document_parties USING btree (document_id);


--
-- Name: document_parties_document_party_role_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_parties_document_party_role_id_idx ON legal.document_parties USING btree (document_party_role_id);


--
-- Name: document_parties_inn_snapshot_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_parties_inn_snapshot_idx ON legal.document_parties USING btree (inn_snapshot);


--
-- Name: document_parties_party_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_parties_party_id_idx ON legal.document_parties USING btree (party_id);


--
-- Name: document_party_roles_active_sort_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_party_roles_active_sort_idx ON legal.document_party_roles USING btree (is_active, sort_order);


--
-- Name: document_party_roles_document_group_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_party_roles_document_group_idx ON legal.document_party_roles USING btree (document_group);


--
-- Name: document_sources_document_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX document_sources_document_idx ON legal.document_sources USING btree (document_id);


--
-- Name: documents_document_date_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX documents_document_date_idx ON legal.documents USING btree (document_date);


--
-- Name: documents_document_type_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX documents_document_type_id_idx ON legal.documents USING btree (document_type_id);


--
-- Name: documents_source_system_external_hash_unique; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX documents_source_system_external_hash_unique ON legal.documents USING btree (source_system, external_hash) WHERE ((source_system IS NOT NULL) AND (external_hash IS NOT NULL));


--
-- Name: documents_source_system_external_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX documents_source_system_external_id_idx ON legal.documents USING btree (source_system, external_id);


--
-- Name: documents_source_system_external_id_unique; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX documents_source_system_external_id_unique ON legal.documents USING btree (document_type_id, source_system, external_id) WHERE ((source_system IS NOT NULL) AND (external_id IS NOT NULL));


--
-- Name: failed_jobs_connection_queue_failed_at_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX failed_jobs_connection_queue_failed_at_index ON legal.laravel_failed_jobs USING btree (connection, queue, failed_at);


--
-- Name: import_runs_file_hash_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX import_runs_file_hash_idx ON legal.import_runs USING btree (file_sha256);


--
-- Name: import_runs_provider_status_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX import_runs_provider_status_idx ON legal.import_runs USING btree (provider, status, started_at);


--
-- Name: jobs_queue_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX jobs_queue_index ON legal.laravel_jobs USING btree (queue);


--
-- Name: kassa_amount_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX kassa_amount_idx ON legal.kassa USING btree (amount);


--
-- Name: kassa_article_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX kassa_article_id_idx ON legal.kassa USING btree (article_id);


--
-- Name: kassa_user_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX kassa_user_id_idx ON legal.kassa USING btree (user_id, "time");


--
-- Name: legal_brand_legal_id_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX legal_brand_legal_id_idx ON legal.legal_brand USING btree (legal_id_owner);


--
-- Name: money_edges_occurred_on_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX money_edges_occurred_on_idx ON legal.money_edges USING btree (occurred_on);


--
-- Name: money_edges_payer_inn_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX money_edges_payer_inn_idx ON legal.money_edges USING btree (payer_inn_snapshot);


--
-- Name: money_edges_recipient_inn_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX money_edges_recipient_inn_idx ON legal.money_edges USING btree (recipient_inn_snapshot);


--
-- Name: sessions_last_activity_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX sessions_last_activity_index ON legal.laravel_sessions USING btree (last_activity);


--
-- Name: sessions_user_id_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX sessions_user_id_index ON legal.laravel_sessions USING btree (user_id);


--
-- Name: source_record_bank_details_account_operation_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX source_record_bank_details_account_operation_idx ON legal.source_record_bank_details USING btree (bank_account_id, external_operation_id);


--
-- Name: source_record_document_details_number_date_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX source_record_document_details_number_date_idx ON legal.source_record_document_details USING btree (document_date, document_number);


--
-- Name: source_record_files_record_hash_unique; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX source_record_files_record_hash_unique ON legal.source_record_files USING btree (source_record_id, file_sha256) WHERE (file_sha256 IS NOT NULL);


--
-- Name: source_record_parties_inn_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX source_record_parties_inn_idx ON legal.source_record_parties USING btree (inn);


--
-- Name: source_record_product_marks_code_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX source_record_product_marks_code_idx ON legal.source_record_product_marks USING btree (mark_code);


--
-- Name: source_record_vat_book_details_entry_unique; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX source_record_vat_book_details_entry_unique ON legal.source_record_vat_book_details USING btree (vat_book_entry_id) WHERE (vat_book_entry_id IS NOT NULL);


--
-- Name: source_records_external_hash_unique; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX source_records_external_hash_unique ON legal.source_records USING btree (source_system, source_record_type, external_hash) WHERE (external_hash IS NOT NULL);


--
-- Name: source_records_external_id_unique; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX source_records_external_id_unique ON legal.source_records USING btree (source_system, source_record_type, external_id) WHERE (external_id IS NOT NULL);


--
-- Name: source_records_received_at_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX source_records_received_at_idx ON legal.source_records USING btree (received_at);


--
-- Name: source_records_type_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX source_records_type_idx ON legal.source_records USING btree (source_record_type, source_system);


--
-- Name: uploaded_files_provider_hash_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX uploaded_files_provider_hash_idx ON legal.uploaded_files USING btree (provider, file_sha256);


--
-- Name: uploaded_files_stored_path_unique; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX uploaded_files_stored_path_unique ON legal.uploaded_files USING btree (stored_path);


--
-- Name: users_is_active_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX users_is_active_index ON legal.laravel_users USING btree (is_active);


--
-- Name: users_role_index; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX users_role_index ON legal.laravel_users USING btree (role);


--
-- Name: vat_book_entries_contractor_inn_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX vat_book_entries_contractor_inn_idx ON legal.vat_book_entries USING btree (contractor_inn);


--
-- Name: vat_book_entries_invoice_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX vat_book_entries_invoice_idx ON legal.vat_book_entries USING btree (invoice_date, invoice_number);


--
-- Name: vat_book_entries_period_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX vat_book_entries_period_idx ON legal.vat_book_entries USING btree (legal_id, book_type, year, quarter);


--
-- Name: vat_book_imports_active_period_key; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX vat_book_imports_active_period_key ON legal.vat_book_imports USING btree (legal_id, book_type, year, quarter) WHERE is_active;


--
-- Name: vat_book_imports_period_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX vat_book_imports_period_idx ON legal.vat_book_imports USING btree (year, quarter, book_type);


--
-- Name: vat_events_contractor_inn_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX vat_events_contractor_inn_idx ON legal.vat_events USING btree (contractor_inn);


--
-- Name: vat_events_occurred_on_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX vat_events_occurred_on_idx ON legal.vat_events USING btree (occurred_on);


--
-- Name: vat_events_period_idx; Type: INDEX; Schema: legal; Owner: -
--

CREATE INDEX vat_events_period_idx ON legal.vat_events USING btree (legal_id, year, quarter);


--
-- Name: vat_events_unique_source_bank_transaction; Type: INDEX; Schema: legal; Owner: -
--

CREATE UNIQUE INDEX vat_events_unique_source_bank_transaction ON legal.vat_events USING btree (source_system, source_document_bank_transaction_id) WHERE (source_document_bank_transaction_id IS NOT NULL);


--
-- Name: accountant_report_links accountant_report_links_document_bank_transaction_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.accountant_report_links
    ADD CONSTRAINT accountant_report_links_document_bank_transaction_id_fkey FOREIGN KEY (document_bank_transaction_id) REFERENCES legal.document_bank_transaction(document_bank_transaction_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: accountant_report_links accountant_report_links_type_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.accountant_report_links
    ADD CONSTRAINT accountant_report_links_type_id_fkey FOREIGN KEY (accountant_report_link_type_id) REFERENCES legal.accountant_report_link_types(accountant_report_link_type_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: accountant_report_links accountant_report_links_vat_book_entry_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.accountant_report_links
    ADD CONSTRAINT accountant_report_links_vat_book_entry_id_fkey FOREIGN KEY (vat_book_entry_id) REFERENCES legal.vat_book_entries(vat_book_entry_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: api_sync_requests api_sync_requests_run_fk; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.api_sync_requests
    ADD CONSTRAINT api_sync_requests_run_fk FOREIGN KEY (api_sync_run_id) REFERENCES legal.api_sync_runs(api_sync_run_id) ON DELETE CASCADE;


--
-- Name: bank_account bank_account_ibfk_2; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.bank_account
    ADD CONSTRAINT bank_account_ibfk_2 FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: bank_account bank_account_ibfk_3; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.bank_account
    ADD CONSTRAINT bank_account_ibfk_3 FOREIGN KEY (bank_id) REFERENCES legal.bank(bank_id);


--
-- Name: counterparty_opening_balances counterparty_opening_balances_legal_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.counterparty_opening_balances
    ADD CONSTRAINT counterparty_opening_balances_legal_id_fkey FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: document_bank_transaction document_bank_transaction_bank_account_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_bank_transaction
    ADD CONSTRAINT document_bank_transaction_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES legal.bank_account(bank_account_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: document_bank_transaction document_bank_transaction_document_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_bank_transaction
    ADD CONSTRAINT document_bank_transaction_document_id_fkey FOREIGN KEY (document_id) REFERENCES legal.documents(document_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: document_parties document_parties_document_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_parties
    ADD CONSTRAINT document_parties_document_id_fkey FOREIGN KEY (document_id) REFERENCES legal.documents(document_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- Name: document_parties document_parties_document_party_role_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_parties
    ADD CONSTRAINT document_parties_document_party_role_id_fkey FOREIGN KEY (document_party_role_id) REFERENCES legal.document_party_roles(document_party_role_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: document_sources document_sources_document_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_sources
    ADD CONSTRAINT document_sources_document_fkey FOREIGN KEY (document_id) REFERENCES legal.documents(document_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: document_sources document_sources_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.document_sources
    ADD CONSTRAINT document_sources_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: documents documents_document_type_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.documents
    ADD CONSTRAINT documents_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES legal.document_types(document_type_id);


--
-- Name: kassa kassa_ibfk_2; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.kassa
    ADD CONSTRAINT kassa_ibfk_2 FOREIGN KEY (article_id) REFERENCES legal.kassa_article(article_id);


--
-- Name: legal_brand legal_brand_ibfk_1; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.legal_brand
    ADD CONSTRAINT legal_brand_ibfk_1 FOREIGN KEY (legal_id_owner) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: legal_tax legal_tax_ibfk_1; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.legal_tax
    ADD CONSTRAINT legal_tax_ibfk_1 FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: legal_tax_period legal_tax_period_ibfk_1; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.legal_tax_period
    ADD CONSTRAINT legal_tax_period_ibfk_1 FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: money_edges money_edges_payer_document_party_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.money_edges
    ADD CONSTRAINT money_edges_payer_document_party_id_fkey FOREIGN KEY (payer_document_party_id) REFERENCES legal.document_parties(document_party_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: money_edges money_edges_recipient_document_party_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.money_edges
    ADD CONSTRAINT money_edges_recipient_document_party_id_fkey FOREIGN KEY (recipient_document_party_id) REFERENCES legal.document_parties(document_party_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: money_edges money_edges_source_document_bank_transaction_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.money_edges
    ADD CONSTRAINT money_edges_source_document_bank_transaction_id_fkey FOREIGN KEY (source_document_bank_transaction_id) REFERENCES legal.document_bank_transaction(document_bank_transaction_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: money_edges money_edges_source_document_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.money_edges
    ADD CONSTRAINT money_edges_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES legal.documents(document_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_record_amounts source_record_amounts_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_amounts
    ADD CONSTRAINT source_record_amounts_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_record_bank_details source_record_bank_details_bank_account_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_bank_details
    ADD CONSTRAINT source_record_bank_details_bank_account_fkey FOREIGN KEY (bank_account_id) REFERENCES legal.bank_account(bank_account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: source_record_bank_details source_record_bank_details_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_bank_details
    ADD CONSTRAINT source_record_bank_details_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_record_document_details source_record_document_details_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_document_details
    ADD CONSTRAINT source_record_document_details_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_record_files source_record_files_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_files
    ADD CONSTRAINT source_record_files_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_record_parties source_record_parties_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_parties
    ADD CONSTRAINT source_record_parties_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_record_product_marks source_record_product_marks_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_product_marks
    ADD CONSTRAINT source_record_product_marks_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_record_vat_book_details source_record_vat_book_details_entry_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_vat_book_details
    ADD CONSTRAINT source_record_vat_book_details_entry_fkey FOREIGN KEY (vat_book_entry_id) REFERENCES legal.vat_book_entries(vat_book_entry_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: source_record_vat_book_details source_record_vat_book_details_import_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_vat_book_details
    ADD CONSTRAINT source_record_vat_book_details_import_fkey FOREIGN KEY (vat_book_import_id) REFERENCES legal.vat_book_imports(vat_book_import_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: source_record_vat_book_details source_record_vat_book_details_legal_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_vat_book_details
    ADD CONSTRAINT source_record_vat_book_details_legal_fkey FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: source_record_vat_book_details source_record_vat_book_details_source_record_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_record_vat_book_details
    ADD CONSTRAINT source_record_vat_book_details_source_record_fkey FOREIGN KEY (source_record_id) REFERENCES legal.source_records(source_record_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: source_records source_records_api_sync_request_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_records
    ADD CONSTRAINT source_records_api_sync_request_fkey FOREIGN KEY (source_api_sync_request_id) REFERENCES legal.api_sync_requests(api_sync_request_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: source_records source_records_vat_book_entry_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.source_records
    ADD CONSTRAINT source_records_vat_book_entry_fkey FOREIGN KEY (source_vat_book_entry_id) REFERENCES legal.vat_book_entries(vat_book_entry_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: uploaded_files uploaded_files_import_run_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.uploaded_files
    ADD CONSTRAINT uploaded_files_import_run_fkey FOREIGN KEY (import_run_id) REFERENCES legal.import_runs(import_run_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: vat_book_entries vat_book_entries_import_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_book_entries
    ADD CONSTRAINT vat_book_entries_import_id_fkey FOREIGN KEY (vat_book_import_id) REFERENCES legal.vat_book_imports(vat_book_import_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vat_book_entries vat_book_entries_legal_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_book_entries
    ADD CONSTRAINT vat_book_entries_legal_id_fkey FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: vat_book_imports vat_book_imports_legal_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_book_imports
    ADD CONSTRAINT vat_book_imports_legal_id_fkey FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: vat_events vat_events_legal_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_events
    ADD CONSTRAINT vat_events_legal_id_fkey FOREIGN KEY (legal_id) REFERENCES legal.legal_own(legal_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: vat_events vat_events_source_document_bank_transaction_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_events
    ADD CONSTRAINT vat_events_source_document_bank_transaction_id_fkey FOREIGN KEY (source_document_bank_transaction_id) REFERENCES legal.document_bank_transaction(document_bank_transaction_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vat_events vat_events_source_document_id_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_events
    ADD CONSTRAINT vat_events_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES legal.documents(document_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vat_events vat_events_source_entry_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_events
    ADD CONSTRAINT vat_events_source_entry_fkey FOREIGN KEY (source_vat_book_entry_id) REFERENCES legal.vat_book_entries(vat_book_entry_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vat_events vat_events_source_import_fkey; Type: FK CONSTRAINT; Schema: legal; Owner: -
--

ALTER TABLE ONLY legal.vat_events
    ADD CONSTRAINT vat_events_source_import_fkey FOREIGN KEY (source_vat_book_import_id) REFERENCES legal.vat_book_imports(vat_book_import_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict LGPbGUm0hTURiqU5b09EA6MGgidNQ7dlKAhxabrT6Tiw46uAFwJ1kesqfyS7Von

--
-- PostgreSQL database dump
--

\restrict eDCe8WdBAUeMNk6b20tGTsI8qfGxO0ChibnBdzeapIeAhzokCfNbHLPo9Us1CCH

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: laravel_migrations; Type: TABLE DATA; Schema: legal; Owner: -
--

COPY legal.laravel_migrations (id, migration, batch) FROM stdin;
1	0001_01_01_000000_create_users_table	1
2	0001_01_01_000001_create_cache_table	1
3	0001_01_01_000002_create_jobs_table	1
4	2026_06_16_120000_create_postgre_legal_schema	2
5	2026_06_16_120100_create_postgre_legal_bank_table	2
6	2026_06_16_120200_create_postgre_legal_bank_account_table	2
7	2026_06_16_120300_create_postgre_legal_bank_transaction_table	2
8	2026_06_16_120400_create_postgre_legal_bank_transaction1c_table	2
9	2026_06_16_120500_create_postgre_legal_kassa_table	2
10	2026_06_16_120600_create_postgre_legal_kassa_article_table	2
11	2026_06_16_120700_create_postgre_legal_legal_table	2
12	2026_06_16_120800_create_postgre_legal_legal_brand_table	2
13	2026_06_16_120900_create_postgre_legal_legal_buh_saldo_table	2
14	2026_06_16_121000_create_postgre_legal_legal_buh_vat_table	2
15	2026_06_16_121100_create_postgre_legal_legal_inn_table	2
16	2026_06_16_121200_create_postgre_legal_legal_kudir_record_table	2
17	2026_06_16_121300_create_postgre_legal_legal_kudir_record_type_table	2
18	2026_06_16_121400_create_postgre_legal_legal_reconciliation_table	2
19	2026_06_16_121500_create_postgre_legal_legal_reconciliation_type_table	2
20	2026_06_16_121600_create_postgre_legal_legal_tax_table	2
21	2026_06_16_121700_create_postgre_legal_legal_tax_period_table	2
22	2026_06_16_121750_create_postgre_legal_document_types_table	2
23	2026_06_16_121800_create_postgre_legal_indexes	2
24	2026_06_16_121900_create_postgre_legal_foreign_keys	2
25	2026_06_16_122000_create_postgre_legal_functions	2
26	2026_06_16_122100_create_postgre_legal_triggers	2
27	2026_06_18_020000_create_postgre_legal_document_parties_table	3
28	2026_06_18_030000_create_postgre_legal_api_sync_runs_table	4
29	2026_06_18_030100_create_postgre_legal_api_sync_requests_table	4
30	2026_06_18_031000_add_bank_account_id_to_postgre_legal_bank_account_table	5
31	2026_06_18_031100_change_postgre_legal_bank_account_primary_key	6
32	2026_06_18_032000_create_postgre_legal_api_credentials_table	7
33	2026_06_19_010000_add_auth_fields_to_users_table	8
34	2026_06_19_020000_move_laravel_tables_to_legal_schema	9
35	2026_06_19_030000_move_migrations_table_to_legal_schema	10
36	2026_06_19_040000_prefix_laravel_engine_tables	11
37	2026_06_20_010000_create_postgre_legal_documents_table	12
38	2026_06_20_020000_create_postgre_legal_document_bank_transaction_table	13
39	2026_06_20_030000_create_postgre_legal_document_party_roles_table	14
40	2026_06_20_040000_add_role_id_to_postgre_legal_document_parties_table	15
41	2026_06_20_050000_drop_role_from_postgre_legal_document_parties_table	16
42	2026_06_20_060000_create_postgre_legal_money_edges_table	17
43	2026_06_20_070000_add_response_body_to_postgre_legal_api_sync_requests_table	18
44	2026_06_20_080000_create_postgre_legal_vat_book_imports_tables	19
45	2026_06_20_090000_create_postgre_legal_vat_events_table	20
46	2026_06_20_100000_add_bank_source_to_postgre_legal_vat_events_table	21
47	2026_06_20_110000_create_postgre_legal_counterparty_opening_balances_table	22
48	2026_06_20_120000_create_postgre_legal_accountant_report_links_tables	23
49	2026_06_20_121000_add_unique_pair_to_postgre_legal_accountant_report_links_table	24
50	2026_06_21_010000_create_postgre_legal_source_records_tables	25
51	2026_06_21_020000_create_postgre_legal_file_acquisition_tables	26
52	2026_06_21_180000_drop_legacy_storage_tables	27
53	2026_06_21_190000_rename_legal_table_and_use_inn_as_legal_id	28
54	2026_06_21_200000_convert_own_legal_ids_to_strings	29
55	2026_06_21_210000_fix_bank_transaction_signed_amount_direction	30
\.


--
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: legal; Owner: -
--

SELECT pg_catalog.setval('legal.migrations_id_seq', 55, true);


--
-- PostgreSQL database dump complete
--

\unrestrict eDCe8WdBAUeMNk6b20tGTsI8qfGxO0ChibnBdzeapIeAhzokCfNbHLPo9Us1CCH

