<?php

namespace App\Support\ReferenceData;

use Illuminate\Support\Facades\DB;

class CurrencyReferenceData
{
    /**
     * @return array<int, array{currency_code: string, alpha_code: string, minor_units: int|null, name_ru: string, name_en: string|null, countries: string|null, included_on: string|null}>
     */
    public static function all(): array
    {
        return [
            ['currency_code' => '004', 'alpha_code' => 'AFA', 'minor_units' => null, 'name_ru' => 'Афгани', 'name_en' => 'Afghani', 'countries' => 'Афганистан', 'included_on' => '26.12.1994 (01.06.2003)'],
            ['currency_code' => '008', 'alpha_code' => 'ALL', 'minor_units' => 2, 'name_ru' => 'Лек', 'name_en' => 'Lek', 'countries' => 'Албания', 'included_on' => '26.12.1994'],
            ['currency_code' => '012', 'alpha_code' => 'DZD', 'minor_units' => 2, 'name_ru' => 'Алжирский динар', 'name_en' => 'Algerian Dinar', 'countries' => 'Алжир', 'included_on' => '26.12.1994'],
            ['currency_code' => '020', 'alpha_code' => 'ADP', 'minor_units' => null, 'name_ru' => 'Андоррская песета', 'name_en' => 'Andorran Peseta', 'countries' => 'Андорра', 'included_on' => '26.12.1994 (01.01.2004)'],
            ['currency_code' => '024', 'alpha_code' => 'AON', 'minor_units' => null, 'name_ru' => 'Новая кванза', 'name_en' => 'New Kwanza', 'countries' => 'Ангола', 'included_on' => '26.12.1994 (05.05.2000)'],
            ['currency_code' => '031', 'alpha_code' => 'AZM', 'minor_units' => null, 'name_ru' => 'Азербайджанский манат', 'name_en' => 'Azerbaijanian Manat', 'countries' => 'Азербайджан', 'included_on' => '26.12.1994 (01.02.2007)'],
            ['currency_code' => '032', 'alpha_code' => 'ARS', 'minor_units' => 2, 'name_ru' => 'Аргентинское песо', 'name_en' => 'Argentine Peso', 'countries' => 'Аргентина', 'included_on' => '26.12.1994'],
            ['currency_code' => '036', 'alpha_code' => 'AUD', 'minor_units' => 2, 'name_ru' => 'Австралийский доллар', 'name_en' => 'Australian Dollar', 'countries' => 'Австралия Кирибати Кокосовые острова Науру Остров Норфолк Остров Рождества Тувалу Острова Херд и Макдональд', 'included_on' => '26.12.1994'],
            ['currency_code' => '040', 'alpha_code' => 'ATS', 'minor_units' => null, 'name_ru' => 'Шиллинг', 'name_en' => 'Schilling', 'countries' => 'Австрия', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '044', 'alpha_code' => 'BSD', 'minor_units' => 2, 'name_ru' => 'Багамский доллар', 'name_en' => 'Bahamian Dollar', 'countries' => 'Багамские Острова', 'included_on' => '26.12.1994'],
            ['currency_code' => '048', 'alpha_code' => 'BHD', 'minor_units' => 3, 'name_ru' => 'Бахрейнский динар', 'name_en' => 'Bahraini Dinar', 'countries' => 'Бахрейн', 'included_on' => '26.12.1994'],
            ['currency_code' => '050', 'alpha_code' => 'BDT', 'minor_units' => 2, 'name_ru' => 'Така', 'name_en' => 'Taka', 'countries' => 'Бангладеш', 'included_on' => '26.12.1994'],
            ['currency_code' => '051', 'alpha_code' => 'AMD', 'minor_units' => 2, 'name_ru' => 'Армянский драм', 'name_en' => 'Armenian Dram', 'countries' => 'Армения', 'included_on' => '26.12.1994'],
            ['currency_code' => '052', 'alpha_code' => 'BBD', 'minor_units' => 2, 'name_ru' => 'Барбадосский доллар', 'name_en' => 'Barbados Dollar', 'countries' => 'Барбадос', 'included_on' => '26.12.1994'],
            ['currency_code' => '056', 'alpha_code' => 'BEF', 'minor_units' => null, 'name_ru' => 'Бельгийский франк', 'name_en' => 'Belgian Franc', 'countries' => 'Бельгия', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '060', 'alpha_code' => 'BMD', 'minor_units' => 2, 'name_ru' => 'Бермудский доллар', 'name_en' => 'Bermudian Dollar', 'countries' => 'Бермудские Острова', 'included_on' => '26.12.1994'],
            ['currency_code' => '064', 'alpha_code' => 'BTN', 'minor_units' => 2, 'name_ru' => 'Нгултрум', 'name_en' => 'Ngultrum', 'countries' => 'Бутан', 'included_on' => '26.12.1994'],
            ['currency_code' => '068', 'alpha_code' => 'BOB', 'minor_units' => 2, 'name_ru' => 'Боливиано', 'name_en' => 'Boliviano', 'countries' => 'Боливия', 'included_on' => '26.12.1994'],
            ['currency_code' => '072', 'alpha_code' => 'BWP', 'minor_units' => 2, 'name_ru' => 'Пула', 'name_en' => 'Pula', 'countries' => 'Ботсвана', 'included_on' => '26.12.1994'],
            ['currency_code' => '084', 'alpha_code' => 'BZD', 'minor_units' => 2, 'name_ru' => 'Белизский доллар', 'name_en' => 'Belize Dollar', 'countries' => 'Белиз', 'included_on' => '26.12.1994'],
            ['currency_code' => '090', 'alpha_code' => 'SBD', 'minor_units' => 2, 'name_ru' => 'Доллар Соломоновых Островов', 'name_en' => 'Solomon Islands Dollar', 'countries' => 'Соломоновы Острова', 'included_on' => '26.12.1994'],
            ['currency_code' => '096', 'alpha_code' => 'BND', 'minor_units' => 2, 'name_ru' => 'Брунейский доллар', 'name_en' => 'Brunei Dollar', 'countries' => 'Бруней', 'included_on' => '26.12.1994'],
            ['currency_code' => '100', 'alpha_code' => 'BGL', 'minor_units' => null, 'name_ru' => 'Лев', 'name_en' => 'Lev', 'countries' => 'Болгария', 'included_on' => '26.12.1994 (01.01.2004)'],
            ['currency_code' => '104', 'alpha_code' => 'MMK', 'minor_units' => 2, 'name_ru' => 'Кьят', 'name_en' => 'Kyat', 'countries' => 'Мьянма', 'included_on' => '26.12.1994'],
            ['currency_code' => '108', 'alpha_code' => 'BIF', 'minor_units' => 0, 'name_ru' => 'Бурундийский франк', 'name_en' => 'Burundi Franc', 'countries' => 'Бурунди', 'included_on' => '26.12.1994'],
            ['currency_code' => '112', 'alpha_code' => 'BYB', 'minor_units' => null, 'name_ru' => 'Белорусский рубль', 'name_en' => 'Belarussian Ruble', 'countries' => 'Беларусь', 'included_on' => '26.12.1994 (01.07.2001)'],
            ['currency_code' => '116', 'alpha_code' => 'KHR', 'minor_units' => 2, 'name_ru' => 'Риель', 'name_en' => 'Riel', 'countries' => 'Камбоджа', 'included_on' => '26.12.1994'],
            ['currency_code' => '124', 'alpha_code' => 'CAD', 'minor_units' => 2, 'name_ru' => 'Канадский доллар', 'name_en' => 'Canadian Dollar', 'countries' => 'Канада', 'included_on' => '26.12.1994'],
            ['currency_code' => '132', 'alpha_code' => 'CVE', 'minor_units' => 2, 'name_ru' => 'Эскудо Кабо-Верде', 'name_en' => 'Cape Verde Escudo', 'countries' => 'Кабо-Верде', 'included_on' => '26.12.1994'],
            ['currency_code' => '136', 'alpha_code' => 'KYD', 'minor_units' => 2, 'name_ru' => 'Доллар Островов Кайман', 'name_en' => 'Cayman Islands Dollar', 'countries' => 'Каймановы Острова', 'included_on' => '26.12.1994'],
            ['currency_code' => '144', 'alpha_code' => 'LKR', 'minor_units' => 2, 'name_ru' => 'Шри-Ланкийская рупия', 'name_en' => 'Sri Lanka Rupee', 'countries' => 'Шри-Ланка', 'included_on' => '26.12.1994'],
            ['currency_code' => '152', 'alpha_code' => 'CLP', 'minor_units' => 0, 'name_ru' => 'Чилийское песо', 'name_en' => 'Chilean Peso', 'countries' => 'Чили', 'included_on' => '26.12.1994'],
            ['currency_code' => '156', 'alpha_code' => 'CNY', 'minor_units' => 2, 'name_ru' => 'Юань', 'name_en' => 'Yuan Renminbi', 'countries' => 'Китай', 'included_on' => '26.12.1994'],
            ['currency_code' => '170', 'alpha_code' => 'COP', 'minor_units' => 2, 'name_ru' => 'Колумбийское песо', 'name_en' => 'Colombian Peso', 'countries' => 'Колумбия', 'included_on' => '26.12.1994'],
            ['currency_code' => '174', 'alpha_code' => 'KMF', 'minor_units' => 0, 'name_ru' => 'Франк Комор', 'name_en' => 'Comoro Franc', 'countries' => 'Коморы', 'included_on' => '26.12.1994'],
            ['currency_code' => '180', 'alpha_code' => 'ZRN', 'minor_units' => null, 'name_ru' => 'Новый заир', 'name_en' => 'New Zaire', 'countries' => 'Заир', 'included_on' => '26.12.1994 (01.01.2001)'],
            ['currency_code' => '188', 'alpha_code' => 'CRC', 'minor_units' => 2, 'name_ru' => 'Коста-риканский колон', 'name_en' => 'Costa Rican Colon', 'countries' => 'Коста-Рика', 'included_on' => '26.12.1994'],
            ['currency_code' => '191', 'alpha_code' => 'HRK', 'minor_units' => 2, 'name_ru' => 'Хорватская куна', 'name_en' => 'Kuna', 'countries' => 'Хорватия', 'included_on' => '26.12.1994'],
            ['currency_code' => '192', 'alpha_code' => 'CUP', 'minor_units' => 2, 'name_ru' => 'Кубинское песо', 'name_en' => 'Cuban Peso', 'countries' => 'Куба', 'included_on' => '26.12.1994'],
            ['currency_code' => '196', 'alpha_code' => 'CYP', 'minor_units' => null, 'name_ru' => 'Кипрский фунт', 'name_en' => 'Cyprus Pound', 'countries' => 'Кипр', 'included_on' => '26.12.1994 (01.11.2008)'],
            ['currency_code' => '203', 'alpha_code' => 'CZK', 'minor_units' => 2, 'name_ru' => 'Чешская крона', 'name_en' => 'Czech Koruna', 'countries' => 'Чехия', 'included_on' => '26.12.1994'],
            ['currency_code' => '208', 'alpha_code' => 'DKK', 'minor_units' => 2, 'name_ru' => 'Датская крона', 'name_en' => 'Danish Krone', 'countries' => 'Дания Гренландия Фарерские острова', 'included_on' => '26.12.1994'],
            ['currency_code' => '214', 'alpha_code' => 'DOP', 'minor_units' => 2, 'name_ru' => 'Доминиканское песо', 'name_en' => 'Dominican Peso', 'countries' => 'Доминиканская Республика', 'included_on' => '26.12.1994'],
            ['currency_code' => '218', 'alpha_code' => 'ECS', 'minor_units' => null, 'name_ru' => 'Сукре', 'name_en' => 'Sucre', 'countries' => 'Эквадор', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '222', 'alpha_code' => 'SVC', 'minor_units' => 2, 'name_ru' => 'Сальвадорский колон', 'name_en' => 'El Salvador Colon', 'countries' => 'Сальвадор', 'included_on' => '26.12.1994'],
            ['currency_code' => '230', 'alpha_code' => 'ETB', 'minor_units' => 2, 'name_ru' => 'Эфиопский быр', 'name_en' => 'Ethiopian Birr', 'countries' => 'Эфиопия', 'included_on' => '26.12.1994'],
            ['currency_code' => '232', 'alpha_code' => 'ERN', 'minor_units' => 2, 'name_ru' => 'Накфа', 'name_en' => 'Nakfa', 'countries' => 'Эритрея', 'included_on' => '01.01.2001'],
            ['currency_code' => '233', 'alpha_code' => 'EEK', 'minor_units' => null, 'name_ru' => 'Крона', 'name_en' => 'Kroon', 'countries' => 'Эстония', 'included_on' => '26.12.1994 (01.01.2011)'],
            ['currency_code' => '238', 'alpha_code' => 'FKP', 'minor_units' => 2, 'name_ru' => 'Фунт Фолклендских островов', 'name_en' => 'Falkland Islands Pound', 'countries' => 'Фолклендские острова', 'included_on' => '26.12.1994'],
            ['currency_code' => '242', 'alpha_code' => 'FJD', 'minor_units' => 2, 'name_ru' => 'Доллар Фиджи', 'name_en' => 'Fiji Dollar', 'countries' => 'Фиджи', 'included_on' => '26.12.1994'],
            ['currency_code' => '246', 'alpha_code' => 'FIM', 'minor_units' => null, 'name_ru' => 'Марка', 'name_en' => 'Markka', 'countries' => 'Финляндия', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '250', 'alpha_code' => 'FRF', 'minor_units' => null, 'name_ru' => 'Французский франк', 'name_en' => 'French Franc', 'countries' => 'Франция', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '262', 'alpha_code' => 'DJF', 'minor_units' => 0, 'name_ru' => 'Франк Джибути', 'name_en' => 'Djibouti Franc', 'countries' => 'Джибути', 'included_on' => '26.12.1994'],
            ['currency_code' => '268', 'alpha_code' => 'GEK', 'minor_units' => null, 'name_ru' => 'Грузинский купон', 'name_en' => 'Georgian Coupon', 'countries' => 'Грузия', 'included_on' => '26.12.1994 (08.12.1999)'],
            ['currency_code' => '270', 'alpha_code' => 'GMD', 'minor_units' => 2, 'name_ru' => 'Даласи', 'name_en' => 'Dalasi', 'countries' => 'Гамбия', 'included_on' => '26.12.1994'],
            ['currency_code' => '276', 'alpha_code' => 'DEM', 'minor_units' => null, 'name_ru' => 'Немецкая марка', 'name_en' => 'Deutsche Mark', 'countries' => 'Германия', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '288', 'alpha_code' => 'GHC', 'minor_units' => null, 'name_ru' => 'Седи', 'name_en' => 'Cedi', 'countries' => 'Гана', 'included_on' => '26.12.1994 (01.01.2010)'],
            ['currency_code' => '292', 'alpha_code' => 'GIP', 'minor_units' => 2, 'name_ru' => 'Гибралтарский фунт', 'name_en' => 'Gibraltar Pound', 'countries' => 'Гибралтар', 'included_on' => '26.12.1994'],
            ['currency_code' => '300', 'alpha_code' => 'GRD', 'minor_units' => null, 'name_ru' => 'Драхма', 'name_en' => 'Drachma', 'countries' => 'Греция', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '320', 'alpha_code' => 'GTQ', 'minor_units' => 2, 'name_ru' => 'Кетсаль', 'name_en' => 'Quetzal', 'countries' => 'Гватемала', 'included_on' => '26.12.1994'],
            ['currency_code' => '324', 'alpha_code' => 'GNF', 'minor_units' => 0, 'name_ru' => 'Гвинейский франк', 'name_en' => 'Guinea Franc', 'countries' => 'Гвинея', 'included_on' => '26.12.1994'],
            ['currency_code' => '328', 'alpha_code' => 'GYD', 'minor_units' => 2, 'name_ru' => 'Гайанский доллар', 'name_en' => 'Guyana Dollar', 'countries' => 'Гайана', 'included_on' => '26.12.1994'],
            ['currency_code' => '332', 'alpha_code' => 'HTG', 'minor_units' => 2, 'name_ru' => 'Гурд', 'name_en' => 'Gourde', 'countries' => 'Гаити', 'included_on' => '26.12.1994'],
            ['currency_code' => '340', 'alpha_code' => 'HNL', 'minor_units' => 2, 'name_ru' => 'Лемпира', 'name_en' => 'Lempira', 'countries' => 'Гондурас', 'included_on' => '26.12.1994'],
            ['currency_code' => '344', 'alpha_code' => 'HKD', 'minor_units' => 2, 'name_ru' => 'Гонконгский доллар', 'name_en' => 'Hong Kong Dollar', 'countries' => 'Гонконг', 'included_on' => '26.12.1994'],
            ['currency_code' => '348', 'alpha_code' => 'HUF', 'minor_units' => 2, 'name_ru' => 'Форинт', 'name_en' => 'Forint', 'countries' => 'Венгрия', 'included_on' => '26.12.1994'],
            ['currency_code' => '352', 'alpha_code' => 'ISK', 'minor_units' => 0, 'name_ru' => 'Исландская крона', 'name_en' => 'Iceland Krona', 'countries' => 'Исландия', 'included_on' => '26.12.1994'],
            ['currency_code' => '356', 'alpha_code' => 'INR', 'minor_units' => 2, 'name_ru' => 'Индийская рупия', 'name_en' => 'Indian Rupee', 'countries' => 'Индия Бутан', 'included_on' => '26.12.1994'],
            ['currency_code' => '360', 'alpha_code' => 'IDR', 'minor_units' => 2, 'name_ru' => 'Рупия', 'name_en' => 'Rupiah', 'countries' => 'Индонезия', 'included_on' => '26.12.1994'],
            ['currency_code' => '364', 'alpha_code' => 'IRR', 'minor_units' => 2, 'name_ru' => 'Иранский риал', 'name_en' => 'Iranian Rial', 'countries' => 'Иран', 'included_on' => '26.12.1994'],
            ['currency_code' => '368', 'alpha_code' => 'IQD', 'minor_units' => 3, 'name_ru' => 'Иракский динар', 'name_en' => 'Iraqi Dinar', 'countries' => 'Ирак', 'included_on' => '26.12.1994'],
            ['currency_code' => '372', 'alpha_code' => 'IEP', 'minor_units' => null, 'name_ru' => 'Ирландский фунт', 'name_en' => 'Irish Pound', 'countries' => 'Ирландия', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '376', 'alpha_code' => 'ILS', 'minor_units' => 2, 'name_ru' => 'Новый израильский шекель', 'name_en' => 'New Israeli Sheqel', 'countries' => 'Израиль', 'included_on' => '26.12.1994'],
            ['currency_code' => '380', 'alpha_code' => 'ITL', 'minor_units' => null, 'name_ru' => 'Итальянская лира', 'name_en' => 'Italian Lira', 'countries' => 'Италия', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '388', 'alpha_code' => 'JMD', 'minor_units' => 2, 'name_ru' => 'Ямайский доллар', 'name_en' => 'Jamaican Dollar', 'countries' => 'Ямайка', 'included_on' => '26.12.1994'],
            ['currency_code' => '392', 'alpha_code' => 'JPY', 'minor_units' => 0, 'name_ru' => 'Иена', 'name_en' => 'Yen', 'countries' => 'Япония', 'included_on' => '26.12.1994'],
            ['currency_code' => '398', 'alpha_code' => 'KZT', 'minor_units' => 2, 'name_ru' => 'Тенге', 'name_en' => 'Tenge', 'countries' => 'Казахстан', 'included_on' => '26.12.1994'],
            ['currency_code' => '400', 'alpha_code' => 'JOD', 'minor_units' => 3, 'name_ru' => 'Иорданский динар', 'name_en' => 'Jordanian Dinar', 'countries' => 'Иордания', 'included_on' => '26.12.1994'],
            ['currency_code' => '404', 'alpha_code' => 'KES', 'minor_units' => 2, 'name_ru' => 'Кенийский шиллинг', 'name_en' => 'Kenyan Shilling', 'countries' => 'Кения', 'included_on' => '26.12.1994'],
            ['currency_code' => '408', 'alpha_code' => 'KPW', 'minor_units' => 2, 'name_ru' => 'Северокорейская вона', 'name_en' => 'North Korean Won', 'countries' => 'КНДР', 'included_on' => '26.12.1994'],
            ['currency_code' => '410', 'alpha_code' => 'KRW', 'minor_units' => 0, 'name_ru' => 'Вона', 'name_en' => 'Won', 'countries' => 'Республика Корея', 'included_on' => '26.12.1994'],
            ['currency_code' => '414', 'alpha_code' => 'KWD', 'minor_units' => 3, 'name_ru' => 'Кувейтский динар', 'name_en' => 'Kuwaiti Dinar', 'countries' => 'Кувейт', 'included_on' => '26.12.1994'],
            ['currency_code' => '417', 'alpha_code' => 'KGS', 'minor_units' => 2, 'name_ru' => 'Сом', 'name_en' => 'Som', 'countries' => 'Кыргызстан', 'included_on' => '26.12.1994'],
            ['currency_code' => '418', 'alpha_code' => 'LAK', 'minor_units' => 2, 'name_ru' => 'Кип', 'name_en' => 'Kip', 'countries' => 'Лаос', 'included_on' => '26.12.1994'],
            ['currency_code' => '422', 'alpha_code' => 'LBP', 'minor_units' => 2, 'name_ru' => 'Ливанский фунт', 'name_en' => 'Lebanese Pound', 'countries' => 'Ливан', 'included_on' => '26.12.1994'],
            ['currency_code' => '426', 'alpha_code' => 'LSL', 'minor_units' => 2, 'name_ru' => 'Лоти', 'name_en' => 'Loti', 'countries' => 'Лесото', 'included_on' => '26.12.1994'],
            ['currency_code' => '428', 'alpha_code' => 'LVL', 'minor_units' => null, 'name_ru' => 'Латвийский лат', 'name_en' => 'Latvian Lats', 'countries' => 'Латвия', 'included_on' => '26.12.1994 (01.01.2014)'],
            ['currency_code' => '430', 'alpha_code' => 'LRD', 'minor_units' => 2, 'name_ru' => 'Либерийский доллар', 'name_en' => 'Liberian Dollar', 'countries' => 'Либерия', 'included_on' => '26.12.1994'],
            ['currency_code' => '434', 'alpha_code' => 'LYD', 'minor_units' => 3, 'name_ru' => 'Ливийский динар', 'name_en' => 'Libyan Dinar', 'countries' => 'Ливия', 'included_on' => '26.12.1994'],
            ['currency_code' => '440', 'alpha_code' => 'LTL', 'minor_units' => null, 'name_ru' => 'Литовский лит', 'name_en' => 'Lithuanian Litas', 'countries' => 'Литва', 'included_on' => '26.12.1994 (01.01.2015)'],
            ['currency_code' => '442', 'alpha_code' => 'LUF', 'minor_units' => null, 'name_ru' => 'Люксембургский франк', 'name_en' => 'Luxembourg Franc', 'countries' => 'Люксембург', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '446', 'alpha_code' => 'MOP', 'minor_units' => 2, 'name_ru' => 'Патака', 'name_en' => 'Pataca', 'countries' => 'Макао', 'included_on' => '26.12.1994'],
            ['currency_code' => '450', 'alpha_code' => 'MGF', 'minor_units' => null, 'name_ru' => 'Малагасийский франк', 'name_en' => 'Malagasy Franc', 'countries' => 'Мадагаскар', 'included_on' => '26.12.1994 (01.02.2007)'],
            ['currency_code' => '454', 'alpha_code' => 'MWK', 'minor_units' => 2, 'name_ru' => 'Квача', 'name_en' => 'Kwacha', 'countries' => 'Малави', 'included_on' => '26.12.1994'],
            ['currency_code' => '458', 'alpha_code' => 'MYR', 'minor_units' => 2, 'name_ru' => 'Малайзийский ринггит', 'name_en' => 'Malaysian Ringgit', 'countries' => 'Малайзия', 'included_on' => '26.12.1994'],
            ['currency_code' => '462', 'alpha_code' => 'MVR', 'minor_units' => 2, 'name_ru' => 'Руфия', 'name_en' => 'Rufiyaa', 'countries' => 'Мальдивы', 'included_on' => '26.12.1994'],
            ['currency_code' => '470', 'alpha_code' => 'MTL', 'minor_units' => null, 'name_ru' => 'Мальтийская лира', 'name_en' => 'Malta Lire', 'countries' => 'Мальта', 'included_on' => '26.12.1994 (01.11.2008)'],
            ['currency_code' => '478', 'alpha_code' => 'MRO', 'minor_units' => 2, 'name_ru' => 'Угия', 'name_en' => 'Ouguiya', 'countries' => 'Мавритания', 'included_on' => '26.12.1994 (01.07.2018)'],
            ['currency_code' => '480', 'alpha_code' => 'MUR', 'minor_units' => 2, 'name_ru' => 'Маврикийская рупия', 'name_en' => 'Mauritius Rupee', 'countries' => 'Маврикий', 'included_on' => '26.12.1994'],
            ['currency_code' => '484', 'alpha_code' => 'MXN', 'minor_units' => 2, 'name_ru' => 'Мексиканское песо', 'name_en' => 'Mexican Peso', 'countries' => 'Мексика', 'included_on' => '26.12.1994'],
            ['currency_code' => '496', 'alpha_code' => 'MNT', 'minor_units' => 2, 'name_ru' => 'Тугрик', 'name_en' => 'Tugrik', 'countries' => 'Монголия', 'included_on' => '26.12.1994'],
            ['currency_code' => '498', 'alpha_code' => 'MDL', 'minor_units' => 2, 'name_ru' => 'Молдавский лей', 'name_en' => 'Moldovan Leu', 'countries' => 'Молдова', 'included_on' => '26.12.1994'],
            ['currency_code' => '504', 'alpha_code' => 'MAD', 'minor_units' => 2, 'name_ru' => 'Марокканский дирхам', 'name_en' => 'Moroccan Dirham', 'countries' => 'Марокко Западная Сахара', 'included_on' => '26.12.1994'],
            ['currency_code' => '508', 'alpha_code' => 'MZM', 'minor_units' => null, 'name_ru' => 'Метикал', 'name_en' => 'Mozambique Metical', 'countries' => 'Мозамбик', 'included_on' => '26.12.1994 (01.01.2007)'],
            ['currency_code' => '512', 'alpha_code' => 'OMR', 'minor_units' => 3, 'name_ru' => 'Оманский риал', 'name_en' => 'Rial Omani', 'countries' => 'Оман', 'included_on' => '26.12.1994'],
            ['currency_code' => '516', 'alpha_code' => 'NAD', 'minor_units' => 2, 'name_ru' => 'Доллар Намибии', 'name_en' => 'Namibia Dollar', 'countries' => 'Намибия', 'included_on' => '26.12.1994'],
            ['currency_code' => '524', 'alpha_code' => 'NPR', 'minor_units' => 2, 'name_ru' => 'Непальская рупия', 'name_en' => 'Nepalese Rupee', 'countries' => 'Непал', 'included_on' => '26.12.1994'],
            ['currency_code' => '528', 'alpha_code' => 'NLG', 'minor_units' => null, 'name_ru' => 'Нидерландский гульден', 'name_en' => 'Netherlands Guilder', 'countries' => 'Нидерланды', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '532', 'alpha_code' => 'ANG', 'minor_units' => 2, 'name_ru' => 'Нидерландский антильский гульден', 'name_en' => 'Netherlands Antillean Guilder', 'countries' => 'Кюрасао Синт-Мартен', 'included_on' => '26.12.1994'],
            ['currency_code' => '533', 'alpha_code' => 'AWG', 'minor_units' => 2, 'name_ru' => 'Арубанский флорин', 'name_en' => 'Aruban Florin', 'countries' => 'Аруба', 'included_on' => '26.12.1994'],
            ['currency_code' => '548', 'alpha_code' => 'VUV', 'minor_units' => 0, 'name_ru' => 'Вату', 'name_en' => 'Vatu', 'countries' => 'Вануату', 'included_on' => '26.12.1994'],
            ['currency_code' => '554', 'alpha_code' => 'NZD', 'minor_units' => 2, 'name_ru' => 'Новозеландский доллар', 'name_en' => 'New Zealand Dollar', 'countries' => 'Новая Зеландия Ниуэ Острова Кука Острова Питкэрн Токелау', 'included_on' => '26.12.1994'],
            ['currency_code' => '558', 'alpha_code' => 'NIO', 'minor_units' => 2, 'name_ru' => 'Золотая кордоба', 'name_en' => 'Cordoba Oro', 'countries' => 'Никарагуа', 'included_on' => '26.12.1994'],
            ['currency_code' => '566', 'alpha_code' => 'NGN', 'minor_units' => 2, 'name_ru' => 'Найра', 'name_en' => 'Naira', 'countries' => 'Нигерия', 'included_on' => '26.12.1994'],
            ['currency_code' => '578', 'alpha_code' => 'NOK', 'minor_units' => 2, 'name_ru' => 'Норвежская крона', 'name_en' => 'Norwegian Krone', 'countries' => 'Норвегия Остров Буве Шпицберген и Ян-Майен', 'included_on' => '26.12.1994'],
            ['currency_code' => '586', 'alpha_code' => 'PKR', 'minor_units' => 2, 'name_ru' => 'Пакистанская рупия', 'name_en' => 'Pakistan Rupee', 'countries' => 'Пакистан', 'included_on' => '26.12.1994'],
            ['currency_code' => '590', 'alpha_code' => 'PAB', 'minor_units' => 2, 'name_ru' => 'Бальбоа', 'name_en' => 'Balboa', 'countries' => 'Панама', 'included_on' => '26.12.1994'],
            ['currency_code' => '598', 'alpha_code' => 'PGK', 'minor_units' => 2, 'name_ru' => 'Кина', 'name_en' => 'Kina', 'countries' => 'Папуа — Новая Гвинея', 'included_on' => '26.12.1994'],
            ['currency_code' => '600', 'alpha_code' => 'PYG', 'minor_units' => 0, 'name_ru' => 'Гуарани', 'name_en' => 'Guarani', 'countries' => 'Парагвай', 'included_on' => '26.12.1994'],
            ['currency_code' => '604', 'alpha_code' => 'PEN', 'minor_units' => 2, 'name_ru' => 'Новый соль', 'name_en' => 'Nuevo Sol', 'countries' => 'Перу', 'included_on' => '26.12.1994'],
            ['currency_code' => '608', 'alpha_code' => 'PHP', 'minor_units' => 2, 'name_ru' => 'Филиппинское песо', 'name_en' => 'Philippine Peso', 'countries' => 'Филиппины', 'included_on' => '26.12.1994'],
            ['currency_code' => '616', 'alpha_code' => 'PLZ', 'minor_units' => null, 'name_ru' => 'Злотый', 'name_en' => 'Zloty', 'countries' => 'Польша', 'included_on' => '26.12.1994 (05.05.2000)'],
            ['currency_code' => '620', 'alpha_code' => 'PTE', 'minor_units' => null, 'name_ru' => 'Португальское эскудо', 'name_en' => 'Portuguese Escudo', 'countries' => 'Португалия', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '624', 'alpha_code' => 'GWP', 'minor_units' => null, 'name_ru' => 'Песо Гвинеи-Бисау', 'name_en' => 'Guinea-Bissau Peso', 'countries' => 'Гвинея-Бисау', 'included_on' => '26.12.1994 (01.09.2010)'],
            ['currency_code' => '626', 'alpha_code' => 'TPE', 'minor_units' => null, 'name_ru' => 'Тиморское эскудо', 'name_en' => 'Timor Escudo', 'countries' => 'Восточный Тимор', 'included_on' => '26.12.1994 (01.06.2003)'],
            ['currency_code' => '634', 'alpha_code' => 'QAR', 'minor_units' => 2, 'name_ru' => 'Катарский риал', 'name_en' => 'Qatari Rial', 'countries' => 'Катар', 'included_on' => '26.12.1994'],
            ['currency_code' => '642', 'alpha_code' => 'ROL', 'minor_units' => null, 'name_ru' => 'Лей', 'name_en' => 'Old Leu', 'countries' => 'Румыния', 'included_on' => '26.12.1994 (01.02.2007)'],
            ['currency_code' => '643', 'alpha_code' => 'RUB', 'minor_units' => 2, 'name_ru' => 'Российский рубль', 'name_en' => 'Russian Ruble', 'countries' => 'Россия', 'included_on' => '01.01.2001'],
            ['currency_code' => '646', 'alpha_code' => 'RWF', 'minor_units' => 0, 'name_ru' => 'Франк Руанды', 'name_en' => 'Rwanda Franc', 'countries' => 'Руанда', 'included_on' => '26.12.1994'],
            ['currency_code' => '654', 'alpha_code' => 'SHP', 'minor_units' => 2, 'name_ru' => 'Фунт Святой Елены', 'name_en' => 'Saint Helena Pound', 'countries' => 'Острова Святой Елены, Вознесения и Тристан-да-Кунья', 'included_on' => '26.12.1994'],
            ['currency_code' => '678', 'alpha_code' => 'STD', 'minor_units' => 2, 'name_ru' => 'Добра', 'name_en' => 'Dobra', 'countries' => 'Сан-Томе и Принсипи', 'included_on' => '26.12.1994 (01.04.2018)'],
            ['currency_code' => '682', 'alpha_code' => 'SAR', 'minor_units' => 2, 'name_ru' => 'Саудовский риял', 'name_en' => 'Saudi Riyal', 'countries' => 'Саудовская Аравия', 'included_on' => '26.12.1994'],
            ['currency_code' => '690', 'alpha_code' => 'SCR', 'minor_units' => 2, 'name_ru' => 'Сейшельская рупия', 'name_en' => 'Seychelles Rupee', 'countries' => 'Сейшельские Острова', 'included_on' => '26.12.1994'],
            ['currency_code' => '694', 'alpha_code' => 'SLL', 'minor_units' => 2, 'name_ru' => 'Леоне', 'name_en' => 'Leone', 'countries' => 'Сьерра-Леоне', 'included_on' => '26.12.1994 (01.10.2022)'],
            ['currency_code' => '702', 'alpha_code' => 'SGD', 'minor_units' => 2, 'name_ru' => 'Сингапурский доллар', 'name_en' => 'Singapore Dollar', 'countries' => 'Сингапур', 'included_on' => '26.12.1994'],
            ['currency_code' => '703', 'alpha_code' => 'SKK', 'minor_units' => null, 'name_ru' => 'Словацкая крона', 'name_en' => 'Slovak Koruna', 'countries' => 'Словакия', 'included_on' => '26.12.1994 (01.01.2009)'],
            ['currency_code' => '704', 'alpha_code' => 'VND', 'minor_units' => 0, 'name_ru' => 'Донг', 'name_en' => 'Dong', 'countries' => 'Вьетнам', 'included_on' => '26.12.1994'],
            ['currency_code' => '705', 'alpha_code' => 'SIT', 'minor_units' => null, 'name_ru' => 'Толар', 'name_en' => 'Tolar', 'countries' => 'Словения', 'included_on' => '26.12.1994 (01.01.2007)'],
            ['currency_code' => '706', 'alpha_code' => 'SOS', 'minor_units' => 2, 'name_ru' => 'Сомалийский шиллинг', 'name_en' => 'Somali Shilling', 'countries' => 'Сомали', 'included_on' => '26.12.1994'],
            ['currency_code' => '710', 'alpha_code' => 'ZAR', 'minor_units' => 2, 'name_ru' => 'Рэнд', 'name_en' => 'Rand', 'countries' => 'Лесото Намибия ЮАР', 'included_on' => '26.12.1994'],
            ['currency_code' => '716', 'alpha_code' => 'ZWD', 'minor_units' => null, 'name_ru' => 'Доллар Зимбабве', 'name_en' => 'Zimbabwe Dollar (old)', 'countries' => 'Зимбабве', 'included_on' => '26.12.1994 (01.01.2007)'],
            ['currency_code' => '724', 'alpha_code' => 'ESP', 'minor_units' => null, 'name_ru' => 'Испанская песета', 'name_en' => 'Spanish Peseta', 'countries' => 'Испания', 'included_on' => '26.12.1994 (01.01.2003)'],
            ['currency_code' => '728', 'alpha_code' => 'SSP', 'minor_units' => 2, 'name_ru' => 'Южносуданский фунт', 'name_en' => 'South Sudanese Pound', 'countries' => 'Южный Судан', 'included_on' => '01.03.2012'],
            ['currency_code' => '736', 'alpha_code' => 'SDD', 'minor_units' => null, 'name_ru' => 'Суданский динар', 'name_en' => 'Sudanese Dinar', 'countries' => 'Судан', 'included_on' => '26.12.1994 (01.12.2007)'],
            ['currency_code' => '740', 'alpha_code' => 'SRG', 'minor_units' => null, 'name_ru' => 'Суринамский гульден', 'name_en' => 'Surinam Guilder', 'countries' => 'Суринам', 'included_on' => '26.12.1994 (01.04.2004)'],
            ['currency_code' => '748', 'alpha_code' => 'SZL', 'minor_units' => 2, 'name_ru' => 'Лилангени', 'name_en' => 'Lilangeni', 'countries' => 'Свазиленд', 'included_on' => '26.12.1994'],
            ['currency_code' => '752', 'alpha_code' => 'SEK', 'minor_units' => 2, 'name_ru' => 'Шведская крона', 'name_en' => 'Swedish Krona', 'countries' => 'Швеция', 'included_on' => '26.12.1994'],
            ['currency_code' => '756', 'alpha_code' => 'CHF', 'minor_units' => 2, 'name_ru' => 'Швейцарский франк', 'name_en' => 'Swiss Franc', 'countries' => 'Лихтенштейн Швейцария', 'included_on' => '26.12.1994'],
            ['currency_code' => '760', 'alpha_code' => 'SYP', 'minor_units' => 2, 'name_ru' => 'Сирийский фунт', 'name_en' => 'Syrian Pound', 'countries' => 'Сирия', 'included_on' => '26.12.1994'],
            ['currency_code' => '762', 'alpha_code' => 'TJR', 'minor_units' => null, 'name_ru' => 'Таджикский рубль', 'name_en' => 'Tajik Ruble', 'countries' => 'Таджикистан', 'included_on' => '26.12.1994 (01.07.2001)'],
            ['currency_code' => '764', 'alpha_code' => 'THB', 'minor_units' => 2, 'name_ru' => 'Бат', 'name_en' => 'Baht', 'countries' => 'Таиланд', 'included_on' => '26.12.1994'],
            ['currency_code' => '776', 'alpha_code' => 'TOP', 'minor_units' => 2, 'name_ru' => 'Паанга', 'name_en' => 'Pa’anga', 'countries' => 'Тонга', 'included_on' => '26.12.1994'],
            ['currency_code' => '780', 'alpha_code' => 'TTD', 'minor_units' => 2, 'name_ru' => 'Доллар Тринидада и Тобаго', 'name_en' => 'Trinidad and Tobago Dollar', 'countries' => 'Тринидад и Тобаго', 'included_on' => '26.12.1994'],
            ['currency_code' => '784', 'alpha_code' => 'AED', 'minor_units' => 2, 'name_ru' => 'Дирхам (ОАЭ)', 'name_en' => 'UAE Dirham', 'countries' => 'ОАЭ', 'included_on' => '26.12.1994'],
            ['currency_code' => '788', 'alpha_code' => 'TND', 'minor_units' => 3, 'name_ru' => 'Тунисский динар', 'name_en' => 'Tunisian Dinar', 'countries' => 'Тунис', 'included_on' => '26.12.1994'],
            ['currency_code' => '792', 'alpha_code' => 'TRL', 'minor_units' => null, 'name_ru' => 'Турецкая лира', 'name_en' => 'Old Turkish Lira', 'countries' => 'Турция', 'included_on' => '26.12.1994 (01.02.2007)'],
            ['currency_code' => '795', 'alpha_code' => 'TMM', 'minor_units' => null, 'name_ru' => 'Манат', 'name_en' => 'Manat', 'countries' => 'Туркменистан', 'included_on' => '26.12.1994 (01.01.2009)'],
            ['currency_code' => '800', 'alpha_code' => 'UGX', 'minor_units' => 2, 'name_ru' => 'Угандийский шиллинг', 'name_en' => 'Uganda Shilling', 'countries' => 'Уганда', 'included_on' => '08.12.1999'],
            ['currency_code' => '804', 'alpha_code' => 'UAK', 'minor_units' => null, 'name_ru' => 'Карбованец (украинский)', 'name_en' => 'Karbovanet', 'countries' => 'Украина', 'included_on' => '26.12.1994 (17.03.1997)'],
            ['currency_code' => '807', 'alpha_code' => 'MKD', 'minor_units' => 2, 'name_ru' => 'Денар', 'name_en' => 'Denar', 'countries' => 'Северная Македония', 'included_on' => '26.12.1994'],
            ['currency_code' => '810', 'alpha_code' => 'RUR', 'minor_units' => null, 'name_ru' => 'Российский рубль', 'name_en' => 'Russian Ruble', 'countries' => 'Россия', 'included_on' => '26.12.1994 (01.01.2004)'],
            ['currency_code' => '818', 'alpha_code' => 'EGP', 'minor_units' => 2, 'name_ru' => 'Египетский фунт', 'name_en' => 'Egyptian Pound', 'countries' => 'Египет', 'included_on' => '26.12.1994'],
            ['currency_code' => '826', 'alpha_code' => 'GBP', 'minor_units' => 2, 'name_ru' => 'Фунт стерлингов', 'name_en' => 'Pound Sterling', 'countries' => 'Великобритания Гернси Джерси Остров Мэн', 'included_on' => '26.12.1994'],
            ['currency_code' => '834', 'alpha_code' => 'TZS', 'minor_units' => 2, 'name_ru' => 'Танзанийский шиллинг', 'name_en' => 'Tanzanian Shilling', 'countries' => 'Танзания', 'included_on' => '26.12.1994'],
            ['currency_code' => '840', 'alpha_code' => 'USD', 'minor_units' => 2, 'name_ru' => 'Доллар США', 'name_en' => 'US Dollar', 'countries' => 'США Американское Самоа Бонайре Синт-Эстатиус Саба Британская Территория в Индийском Океане Американские Виргинские Острова Британские Виргинские острова Восточный Тимор Гаити Гуам Внешние малые острова США Маршалловы Острова Микронезия Теркс и Кайкос Палау Панама Пуэрто-Рико Сальвадор Северные Марианские Острова Эквадор', 'included_on' => '26.12.1994'],
            ['currency_code' => '858', 'alpha_code' => 'UYU', 'minor_units' => 2, 'name_ru' => 'Уругвайское песо', 'name_en' => 'Peso Uruguayo', 'countries' => 'Уругвай', 'included_on' => '08.12.1999'],
            ['currency_code' => '860', 'alpha_code' => 'UZS', 'minor_units' => 2, 'name_ru' => 'Узбекский сум', 'name_en' => 'Uzbekistan Sum', 'countries' => 'Узбекистан', 'included_on' => '26.12.1994'],
            ['currency_code' => '862', 'alpha_code' => 'VEB', 'minor_units' => null, 'name_ru' => 'Боливар', 'name_en' => 'Bolivar', 'countries' => 'Венесуэла', 'included_on' => '26.12.1994 (01.01.2010)'],
            ['currency_code' => '882', 'alpha_code' => 'WST', 'minor_units' => 2, 'name_ru' => 'Тала', 'name_en' => 'Tala', 'countries' => 'Самоа', 'included_on' => '26.12.1994'],
            ['currency_code' => '886', 'alpha_code' => 'YER', 'minor_units' => 2, 'name_ru' => 'Йеменский риал', 'name_en' => 'Yemeni Rial', 'countries' => 'Йемен', 'included_on' => '26.12.1994'],
            ['currency_code' => '890', 'alpha_code' => 'YUN', 'minor_units' => null, 'name_ru' => 'Югославский динар', 'name_en' => 'Yugoslavian Dinar', 'countries' => 'Югославия', 'included_on' => '26.12.1994 (01.01.2001)'],
            ['currency_code' => '891', 'alpha_code' => 'CSD', 'minor_units' => null, 'name_ru' => 'Сербский динар', 'name_en' => 'Serbian Dinar', 'countries' => 'Сербия и Черногория', 'included_on' => '01.01.2004 (01.02.2007)'],
            ['currency_code' => '894', 'alpha_code' => 'ZMK', 'minor_units' => null, 'name_ru' => 'Замбийская квача', 'name_en' => 'Zambian Kwacha', 'countries' => 'Замбия', 'included_on' => '26.12.1994 (01.01.2013)'],
            ['currency_code' => '901', 'alpha_code' => 'TWD', 'minor_units' => 2, 'name_ru' => 'Новый тайваньский доллар', 'name_en' => 'New Taiwan Dollar', 'countries' => 'Китайская Республика', 'included_on' => '26.12.1994'],
            ['currency_code' => '925', 'alpha_code' => 'SLE', 'minor_units' => 2, 'name_ru' => 'Леоне', 'name_en' => 'Leone', 'countries' => 'Сьерра-Леоне', 'included_on' => '01.07.2022'],
            ['currency_code' => '929', 'alpha_code' => 'MRU', 'minor_units' => 2, 'name_ru' => 'Угия', 'name_en' => 'Ouguiya', 'countries' => 'Мавритания', 'included_on' => '01.07.2018'],
            ['currency_code' => '930', 'alpha_code' => 'STN', 'minor_units' => 2, 'name_ru' => 'Добра', 'name_en' => 'Dobra', 'countries' => 'Сан-Томе и Принсипи', 'included_on' => '01.04.2018'],
            ['currency_code' => '931', 'alpha_code' => 'CUC', 'minor_units' => 2, 'name_ru' => 'Конвертируемое песо', 'name_en' => 'Peso Convertible', 'countries' => 'Куба', 'included_on' => '01.09.2009'],
            ['currency_code' => '932', 'alpha_code' => 'ZWL', 'minor_units' => 2, 'name_ru' => 'Доллар Зимбабве', 'name_en' => 'Zimbabwe Dollar', 'countries' => 'Зимбабве', 'included_on' => '01.07.2009'],
            ['currency_code' => '933', 'alpha_code' => 'BYN', 'minor_units' => 2, 'name_ru' => 'Белорусский рубль', 'name_en' => 'Belarusian Ruble', 'countries' => 'Беларусь', 'included_on' => '01.07.2016'],
            ['currency_code' => '934', 'alpha_code' => 'TMT', 'minor_units' => 2, 'name_ru' => 'Новый туркменский манат', 'name_en' => 'Turkmenistan New Manat', 'countries' => 'Туркменистан', 'included_on' => '01.01.2009'],
            ['currency_code' => '935', 'alpha_code' => 'ZWR', 'minor_units' => null, 'name_ru' => 'Доллар Зимбабве', 'name_en' => 'Zimbabwe Dollar', 'countries' => 'Зимбабве', 'included_on' => '01.01.2009 (01.01.2010)'],
            ['currency_code' => '936', 'alpha_code' => 'GHS', 'minor_units' => 2, 'name_ru' => 'Ганский седи', 'name_en' => 'Ghana Cedi', 'countries' => 'Гана', 'included_on' => '01.12.2007'],
            ['currency_code' => '937', 'alpha_code' => 'VEF', 'minor_units' => 2, 'name_ru' => 'Боливар фуэрте', 'name_en' => 'Bolívar', 'countries' => 'Венесуэла', 'included_on' => '01.12.2007'],
            ['currency_code' => '938', 'alpha_code' => 'SDG', 'minor_units' => 2, 'name_ru' => 'Суданский фунт', 'name_en' => 'Sudanese Pound', 'countries' => 'Судан', 'included_on' => '01.08.2007'],
            ['currency_code' => '940', 'alpha_code' => 'UYI', 'minor_units' => 0, 'name_ru' => 'Уругвайское песо в индексированных единицах', 'name_en' => 'Urguguay Peso en Unidades Indexadas', 'countries' => 'Уругвай', 'included_on' => '01.02.2007'],
            ['currency_code' => '941', 'alpha_code' => 'RSD', 'minor_units' => 2, 'name_ru' => 'Сербский динар', 'name_en' => 'Serbian Dinar', 'countries' => 'Сербия', 'included_on' => '01.02.2007'],
            ['currency_code' => '942', 'alpha_code' => 'ZWN', 'minor_units' => null, 'name_ru' => 'Новый доллар Зимбабве', 'name_en' => 'Zimbabwe Dollar (new)', 'countries' => 'Зимбабве', 'included_on' => '01.01.2007 (01.02.2007)'],
            ['currency_code' => '943', 'alpha_code' => 'MZN', 'minor_units' => 2, 'name_ru' => 'Мозамбикский метикал', 'name_en' => 'Mozambique Metical', 'countries' => 'Мозамбик', 'included_on' => '01.01.2007'],
            ['currency_code' => '944', 'alpha_code' => 'AZN', 'minor_units' => 2, 'name_ru' => 'Азербайджанский манат', 'name_en' => 'Azerbaijanian Manat', 'countries' => 'Азербайджан', 'included_on' => '01.01.2006'],
            ['currency_code' => '946', 'alpha_code' => 'RON', 'minor_units' => 2, 'name_ru' => 'Новый румынский лей', 'name_en' => 'Romanian Leu', 'countries' => 'Румыния', 'included_on' => '01.07.2005'],
            ['currency_code' => '947', 'alpha_code' => 'CHE', 'minor_units' => 2, 'name_ru' => 'WIR-евро', 'name_en' => 'WIR Euro', 'countries' => 'WIR-банк (Швейцария)', 'included_on' => '—'],
            ['currency_code' => '948', 'alpha_code' => 'CHW', 'minor_units' => 2, 'name_ru' => 'WIR-франк', 'name_en' => 'WIR Franc', 'countries' => 'WIR-банк (Швейцария)', 'included_on' => '—'],
            ['currency_code' => '949', 'alpha_code' => 'TRY', 'minor_units' => 2, 'name_ru' => 'Турецкая лира', 'name_en' => 'Turkish Lira', 'countries' => 'Турция', 'included_on' => '01.04.2005'],
            ['currency_code' => '950', 'alpha_code' => 'XAF', 'minor_units' => 0, 'name_ru' => 'Франк КФА BEAC', 'name_en' => 'CFA Franc BEAC', 'countries' => 'Габон Камерун Республика Конго ЦАР Чад Экваториальная Гвинея', 'included_on' => '26.12.1994'],
            ['currency_code' => '951', 'alpha_code' => 'XCD', 'minor_units' => 2, 'name_ru' => 'Восточно-карибский доллар', 'name_en' => 'East Caribbean Dollar', 'countries' => 'Ангилья Антигуа и Барбуда Гренада Доминика Монтсеррат Сент-Винсент и Гренадины Сент-Китс и Невис Сент-Люсия', 'included_on' => '26.12.1994'],
            ['currency_code' => '952', 'alpha_code' => 'XOF', 'minor_units' => 0, 'name_ru' => 'Франк КФА BCEAO', 'name_en' => 'CFA Franc BCEAO', 'countries' => 'Бенин Буркина-Фасо Гвинея-Бисау Кот-д’Ивуар Мали Нигер Сенегал Того', 'included_on' => '26.12.1994'],
            ['currency_code' => '953', 'alpha_code' => 'XPF', 'minor_units' => 0, 'name_ru' => 'Франк КФП', 'name_en' => 'CFP Franc', 'countries' => 'Французская Полинезия Новая Каледония Уоллис и Футуна', 'included_on' => '26.12.1994'],
            ['currency_code' => '954', 'alpha_code' => 'XEU', 'minor_units' => null, 'name_ru' => 'ЭКЮ (единица европейской валюты)', 'name_en' => 'European Currency Unit (E.C.U.)', 'countries' => 'Европейский фонд финансового сотрудничества', 'included_on' => '26.12.1994 (01.01.2001)'],
            ['currency_code' => '955', 'alpha_code' => 'XBA', 'minor_units' => null, 'name_ru' => 'Европейская составная единица EURCO', 'name_en' => 'European Composite Unit (EURCO)', 'countries' => 'Европейские сообщества', 'included_on' => '—'],
            ['currency_code' => '956', 'alpha_code' => 'XBB', 'minor_units' => null, 'name_ru' => 'Европейская валютная единица EMU-6', 'name_en' => 'European Monetary Unit (E.M.U.-6)', 'countries' => 'Европейские сообщества', 'included_on' => '—'],
            ['currency_code' => '957', 'alpha_code' => 'XBC', 'minor_units' => null, 'name_ru' => 'Европейская расчётная единица EUA-9', 'name_en' => 'European Unit of Account 9 (E.U.A.-9)', 'countries' => 'Европейские сообщества', 'included_on' => '—'],
            ['currency_code' => '958', 'alpha_code' => 'XBD', 'minor_units' => null, 'name_ru' => 'Европейская расчётная единица EUA-17', 'name_en' => 'European Unit of Account 17 (E.U.A.-17)', 'countries' => 'Европейские сообщества', 'included_on' => '—'],
            ['currency_code' => '959', 'alpha_code' => 'XAU', 'minor_units' => null, 'name_ru' => 'Золото (тройская унция)', 'name_en' => 'Gold', 'countries' => '—', 'included_on' => '—'],
            ['currency_code' => '960', 'alpha_code' => 'XDR', 'minor_units' => null, 'name_ru' => 'СДР (специальные права заимствования)', 'name_en' => 'SDR (Special Drawing Right)', 'countries' => 'Международный валютный фонд', 'included_on' => '26.12.1994'],
            ['currency_code' => '961', 'alpha_code' => 'XAG', 'minor_units' => null, 'name_ru' => 'Серебро (тройская унция)', 'name_en' => 'Silver', 'countries' => '—', 'included_on' => '—'],
            ['currency_code' => '962', 'alpha_code' => 'XPT', 'minor_units' => null, 'name_ru' => 'Платина (тройская унция)', 'name_en' => 'Platinum', 'countries' => '—', 'included_on' => '—'],
            ['currency_code' => '963', 'alpha_code' => 'XTS', 'minor_units' => null, 'name_ru' => 'Тестовый код', 'name_en' => 'Testing Code', 'countries' => '—', 'included_on' => '—'],
            ['currency_code' => '964', 'alpha_code' => 'XPD', 'minor_units' => null, 'name_ru' => 'Палладий (тройская унция)', 'name_en' => 'Palladium', 'countries' => '—', 'included_on' => '—'],
            ['currency_code' => '965', 'alpha_code' => 'XUA', 'minor_units' => null, 'name_ru' => 'Расчётная единица ADB', 'name_en' => 'ADB Unit of Account', 'countries' => 'Африканский банк развития', 'included_on' => '—'],
            ['currency_code' => '967', 'alpha_code' => 'ZMW', 'minor_units' => 2, 'name_ru' => 'Замбийская квача', 'name_en' => 'Zambian Kwacha', 'countries' => 'Замбия', 'included_on' => '26.12.1994'],
            ['currency_code' => '968', 'alpha_code' => 'SRD', 'minor_units' => 2, 'name_ru' => 'Суринамский доллар', 'name_en' => 'Surinam Dollar', 'countries' => 'Суринам', 'included_on' => '01.04.2004'],
            ['currency_code' => '969', 'alpha_code' => 'MGA', 'minor_units' => 2, 'name_ru' => 'Малагасийский ариари', 'name_en' => 'Malagasy Ariary', 'countries' => 'Мадагаскар', 'included_on' => '01.01.2004'],
            ['currency_code' => '970', 'alpha_code' => 'COU', 'minor_units' => 2, 'name_ru' => 'Единица реальной стоимости', 'name_en' => 'Unidad de Valor Real', 'countries' => 'Колумбия', 'included_on' => '01.01.2004'],
            ['currency_code' => '971', 'alpha_code' => 'AFN', 'minor_units' => 2, 'name_ru' => 'Афгани', 'name_en' => 'Afghani', 'countries' => 'Афганистан', 'included_on' => '01.06.2003'],
            ['currency_code' => '972', 'alpha_code' => 'TJS', 'minor_units' => 2, 'name_ru' => 'Сомони', 'name_en' => 'Somoni', 'countries' => 'Таджикистан', 'included_on' => '01.01.2001'],
            ['currency_code' => '973', 'alpha_code' => 'AOA', 'minor_units' => 2, 'name_ru' => 'Кванза', 'name_en' => 'Kwanza', 'countries' => 'Ангола', 'included_on' => '05.05.2000'],
            ['currency_code' => '975', 'alpha_code' => 'BGN', 'minor_units' => 2, 'name_ru' => 'Болгарский лев', 'name_en' => 'Bulgarian Lev', 'countries' => 'Болгария', 'included_on' => '05.05.2000'],
            ['currency_code' => '976', 'alpha_code' => 'CDF', 'minor_units' => 2, 'name_ru' => 'Конголезский франк', 'name_en' => 'Congolese Franc', 'countries' => 'ДР Конго', 'included_on' => '05.05.2000'],
            ['currency_code' => '977', 'alpha_code' => 'BAM', 'minor_units' => 2, 'name_ru' => 'Конвертируемая марка', 'name_en' => 'Convertible Mark', 'countries' => 'Босния и Герцеговина', 'included_on' => '01.01.2001'],
            ['currency_code' => '978', 'alpha_code' => 'EUR', 'minor_units' => 2, 'name_ru' => 'Евро', 'name_en' => 'Euro', 'countries' => 'Австрия Аландские острова Андорра Бельгия Ватикан Гваделупа Германия Греция Ирландия Испания Италия Кипр Латвия Люксембург Майотта Мальта Мартиника Монако Нидерланды Португалия Реюньон Сан-Марино Сен-Бартелеми Сен-Мартен Словакия Словения Сен-Пьер и Микелон Финляндия Франция Французская Гвиана Французские Южные и Антарктические территории Черногория Эстония Литва', 'included_on' => '16.12.1998'],
            ['currency_code' => '979', 'alpha_code' => 'MXV', 'minor_units' => 2, 'name_ru' => 'Мексиканская инверсионная единица', 'name_en' => 'Mexican Unidad de Inversion', 'countries' => 'Мексика', 'included_on' => '—'],
            ['currency_code' => '980', 'alpha_code' => 'UAH', 'minor_units' => 2, 'name_ru' => 'Гривна', 'name_en' => 'Hryvnia', 'countries' => 'Украина', 'included_on' => '17.03.1997'],
            ['currency_code' => '981', 'alpha_code' => 'GEL', 'minor_units' => 2, 'name_ru' => 'Лари', 'name_en' => 'Lari', 'countries' => 'Грузия', 'included_on' => '08.12.1999'],
            ['currency_code' => '984', 'alpha_code' => 'BOV', 'minor_units' => 2, 'name_ru' => 'Мвдол', 'name_en' => 'Mvdol', 'countries' => 'Боливия', 'included_on' => '—'],
            ['currency_code' => '985', 'alpha_code' => 'PLN', 'minor_units' => 2, 'name_ru' => 'Злотый', 'name_en' => 'Zloty', 'countries' => 'Польша', 'included_on' => '08.12.1999'],
            ['currency_code' => '986', 'alpha_code' => 'BRL', 'minor_units' => 2, 'name_ru' => 'Бразильский реал', 'name_en' => 'Brazilian Real', 'countries' => 'Бразилия', 'included_on' => '17.03.1997'],
            ['currency_code' => '987', 'alpha_code' => 'BRR', 'minor_units' => null, 'name_ru' => 'Крузейро реал', 'name_en' => 'Cruzeiro Real', 'countries' => 'Бразилия', 'included_on' => '26.12.1994 (17.03.1997)'],
            ['currency_code' => '990', 'alpha_code' => 'CLF', 'minor_units' => 0, 'name_ru' => 'Единица развития', 'name_en' => 'Unidades de Fomento', 'countries' => 'Чили', 'included_on' => '—'],
            ['currency_code' => '994', 'alpha_code' => 'XSU', 'minor_units' => null, 'name_ru' => 'Сукре', 'name_en' => 'Sucre', 'countries' => 'Единая система региональных взаиморасчётов', 'included_on' => '—'],
            ['currency_code' => '997', 'alpha_code' => 'USN', 'minor_units' => 2, 'name_ru' => 'Доллар следующего дня', 'name_en' => 'US Dollar (Next day)', 'countries' => 'США', 'included_on' => '—'],
            ['currency_code' => '998', 'alpha_code' => 'USS', 'minor_units' => 2, 'name_ru' => 'Доллар того же дня', 'name_en' => 'US Dollar (Same day)', 'countries' => 'США', 'included_on' => '—'],
            ['currency_code' => '999', 'alpha_code' => 'XXX', 'minor_units' => null, 'name_ru' => 'Без валюты', 'name_en' => 'No Currency', 'countries' => '—', 'included_on' => '—'],
        ];
    }

    public static function seed(): void
    {
        $now = now();

        foreach (self::all() as $currency) {
            DB::table('legal.currencies')->updateOrInsert(
                ['currency_code' => $currency['currency_code']],
                [
                    'alpha_code' => $currency['alpha_code'],
                    'minor_units' => $currency['minor_units'],
                    'name_ru' => $currency['name_ru'],
                    'name_en' => $currency['name_en'],
                    'countries' => $currency['countries'],
                    'included_on' => $currency['included_on'],
                    'source' => 'okv_wikipedia',
                    'is_active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );

            foreach ([
                $currency['currency_code'] => 'numeric',
                $currency['alpha_code'] => 'alpha',
            ] as $alias => $type) {
                DB::table('legal.currency_aliases')->updateOrInsert(
                    ['currency_alias' => strtoupper((string) $alias)],
                    [
                        'currency_code' => $currency['currency_code'],
                        'alias_type' => $type,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ]
                );
            }
        }
    }
}
